<?php
/*
Template Name: ES_MERIDIAN
*/
?>
<?php
echo "<!DOCTYPE html>\n"; 
echo "<head>\n"; 
echo "	<meta charset=\"utf-8\">\n"; 
echo "    <link rel=\"icon\" type=\"image/png\" href=\"http://gmtest.ru/wp-content/uploads/2013/09/favicon.png\" />\n"; 
echo "	<title>«Easy Steps» - Программа проверки точности глюкометра</title>\n"; 
echo "	<style type=\"text/css\">\n"; 
echo "	@media print\n"; 
echo "	            {\n"; 
echo "	            .more {\n"; 
echo "	                 page-break-before: always;\n"; 
echo "	                }\n"; 
echo "	            li{\n"; 
echo "	            	margin-bottom: 5px;\n"; 
echo "	            }\n"; 
echo "	            #visible\n"; 
echo "	            {\n"; 
echo "	            	display: block;\n"; 
echo "	            }\n"; 
echo "	            #invisible\n"; 
echo "	            {\n"; 
echo "	            	display: none;\n"; 
echo "	            }\n"; 
echo "	            .body\n"; 
echo "	            {\n"; 
echo "	            	width:900px;\n"; 
echo "	            	margin:10px auto;\n"; 
echo "	            }\n"; 
echo "	            .header\n"; 
echo "	            {\n"; 
echo "	            	color:#333;\n"; 
echo "	            	font-family:Arial;\n"; 
echo "	            	font-size:16pt;\n"; 
echo "	            	width: 860px; \n"; 
echo "	            	background:url('http://gmtest.ru/wp-content/themes/mio/images/nav_bg.png') repeat-x scroll top center #f0f0f0;\n"; 
echo "	            	border-radius:4px;\n"; 
echo "	            	margin: 5px 0px 25px 20px;\n"; 
echo "	            	padding: 0px;\n"; 
echo "	            	border:1px solid #bdbdbd;\n"; 
echo "	            	vertical-align:middle;\n"; 
echo "	            	text-shadow: 1px 1px #fff;\n"; 
echo "	            	height:35px;\n"; 
echo "	            	text-align: center;\n"; 
echo "	            }\n"; 
echo "	            a\n"; 
echo "	    		{\n"; 
echo "	    			text-align:justify;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			margin-left: 12px;\n"; 
echo "	    			font-size:10pt;\n"; 
echo "	    			color:#343593;\n"; 
echo "	    			text-decoration: none;\n"; 
echo "	    			font-weight: normal;\n"; 
echo "	    		}\n"; 
echo "	    		\n"; 
echo "	    		.link\n"; 
echo "	    		{\n"; 
echo "	    			text-align:justify;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			margin-left: 0px;\n"; 
echo "	    			font-size:10pt;\n"; 
echo "	    			color:#343593;\n"; 
echo "	    			text-decoration: underline;\n"; 
echo "	    			font-weight: normal;\n"; 
echo "	    		}\n"; 
echo "	    		.link:hover\n"; 
echo "	    		{\n"; 
echo "	    			text-align:justify;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			margin-left: 0px;\n"; 
echo "	    			font-size:10pt;\n"; 
echo "	    			color:#0c9adc;\n"; 
echo "	    			text-decoration: none;\n"; 
echo "	    			font-weight: normal;\n"; 
echo "	    		}\n"; 
echo "	    		p\n"; 
echo "	    		{\n"; 
echo "	    			text-align:center;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:12pt;\n"; 
echo "	    			color:#333;\n"; 
echo "	    		}\n"; 
echo "	    		h1\n"; 
echo "	    		{\n"; 
echo "	    			text-align:center;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:12pt;\n"; 
echo "	    			color:#333;\n"; 
echo "	    			font-weight: normal;\n"; 
echo "	    		}\n"; 
echo "	    		.rt_none \n"; 
echo "	    		{\n"; 
echo "	    			display: none;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    		}\n"; 
echo "	    \n"; 
echo "	    		.rt_gray \n"; 
echo "	    		{\n"; 
echo "	    			margin:20px auto;\n"; 
echo "	    			width:860px;\n"; 
echo "	    			margin-top: 5px;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			border-collapse:collapse;		\n"; 
echo "	    			border: 1px solid #b9b9b9;\n"; 
echo "	    			background-color: #e1e1e1;\n"; 
echo "	    			display: block;\n"; 
echo "	    		}\n"; 
echo "	    		.rt_gray td { border: 1px solid #b9b9b9; padding: 5px;border-radius:4px;	 }\n"; 
echo "	    		.rt_green \n"; 
echo "	    		{\n"; 
echo "	    			margin:20px auto;\n"; 
echo "	    			width:860px;\n"; 
echo "	    			margin-top: 5px;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			border-collapse:collapse;		\n"; 
echo "	    			border: 1px solid #00af5a;\n"; 
echo "	    			background-color: #cef8ce;\n"; 
echo "	    			display: block;\n"; 
echo "	    		}\n"; 
echo "	    		.rt_green td { border: 1px solid #00af5a; padding: 5px;border-radius:4px;	 }\n"; 
echo "	    		.rt_green #reportTitle {text-align: center; font-family:Arial;font-size: 14pt; color: #188338; }\n"; 
echo "	    		\n"; 
echo "	    		.rt_red\n"; 
echo "	    		{\n"; 
echo "	    			margin:20px auto;\n"; 
echo "	    			width:860px;\n"; 
echo "	    			margin-top: 5px;\n"; 
echo "	    			border-collapse:collapse;	\n"; 
echo "	    			border-radius:4px;	\n"; 
echo "	    			border: 1px solid #ed1c24;\n"; 
echo "	    			background-color: #f7e2e2;\n"; 
echo "	    			display: block;			\n"; 
echo "	    		}\n"; 
echo "	    		.rt_red td { border: 1px solid #ed1c24; padding: 5px;border-radius:4px;}\n"; 
echo "	    		.rt_red #reportTitle {text-align: center; font-family:Arial; font-size: 14pt; color: #ed1c24; }\n"; 
echo "	    		#testReport {font-family:Arial; font-size:12pt; text-align:center; color:#333;}\n"; 
echo "	    		.report_note \n"; 
echo "	    		{\n"; 
echo "	    			border-collapse:collapse;			\n"; 
echo "	    			border: 0;			\n"; 
echo "	    			background: #fff;\n"; 
echo "	    			border-radius:4px	;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:12pt;\n"; 
echo "	    			color:#333;\n"; 
echo "	    			text-align:justify;\n"; 
echo "	    			padding:5px;\n"; 
echo "	    		}\n"; 
echo "	    		.report_note td {border: 0;}\n"; 
echo "	    		\n"; 
echo "	    		.cube {border: 2px solid #ed1c24; font-size: 14pt; padding: 2px; margin: 0px 4px 0px 0px; font-family:Arial; border-radius:4px;}\n"; 
echo "	    		\n"; 
echo "	    		#Anal {text-align: center;font-family:Arial;font-size:14pt;}\n"; 
echo "	    		#Anal1 {text-align: center;font-family:Arial;font-size:14pt;}\n"; 
echo "	    		#yourResult {text-align: center;font-family:Arial;font-size:12pt; vertical-align: middle;}\n"; 
echo "	    		#yourRange {text-align: center;font-family:Arial;font-size:12pt;vertical-align: middle;}\n"; 
echo "	    		\n"; 
echo "	    		#error1 \n"; 
echo "	    		{\n"; 
echo "	    			color:#ed1c24; display: none; margin:20px auto; border: 1px solid red;\n"; 
echo "	    			border-radius:4px; background-color:#f7e2e2; text-align:center; width:600px;font-family:Arial;	font-size:14pt;\n"; 
echo "	    		}\n"; 
echo "	    		#error2 \n"; 
echo "	    		{\n"; 
echo "	    			color:#ed1c24; display: none; margin:20px auto; border: 1px solid red;\n"; 
echo "	    			border-radius:4px; background-color:#f7e2e2; text-align:center; width:600px;font-family:Arial;	font-size:14pt;\n"; 
echo "	    		}\n"; 
echo "	    		#error3 \n"; 
echo "	    		{\n"; 
echo "	    			color:#ed1c24; display: none; margin:20px auto; border: 1px solid red;\n"; 
echo "	    			border-radius:4px; background-color:#f7e2e2; text-align:center; width:600px;font-family:Arial;	font-size:14pt;\n"; 
echo "	    		}\n"; 
echo "	    		#error4 \n"; 
echo "	    		{\n"; 
echo "	    			color:#333; display: none; font-family:Arial; font-size:14pt;\n"; 
echo "	    		}\n"; 
echo "	    		#error5 \n"; 
echo "	    		{\n"; 
echo "	    			color:#333; display: none; font-family:Arial; font-size:14pt;\n"; 
echo "	    		}\n"; 
echo "	    		#error6 \n"; 
echo "	    		{\n"; 
echo "	    				color:#ed1c24; display: none; margin:20px auto; border: 1px solid red;\n"; 
echo "	    				border-radius:4px; background-color:#f7e2e2; text-align:center; width:600px;font-family:Arial;	font-size:14pt;\n"; 
echo "	    		}\n"; 
echo "	    		#error7 \n"; 
echo "	    		{\n"; 
echo "	    				color:#ed1c24; display: none; margin:20px auto; border: 1px solid red;\n"; 
echo "	    				border-radius:4px; background-color:#f7e2e2; text-align:center; width:600px;font-family:Arial;	font-size:14pt;\n"; 
echo "	    		}\n"; 
echo "	    		#error8 \n"; 
echo "	    		{\n"; 
echo "	    			color:#333; display: none; font-family:Arial; font-size:14pt;\n"; 
echo "	    		}\n"; 
echo "	    		#printer \n"; 
echo "	    		{\n"; 
echo "	    			display: none;\n"; 
echo "	    		}\n"; 
echo "	    		#logo\n"; 
echo "	    		{\n"; 
echo "	    			opacity:0.5;transition:opacity 0.8s;-moz-transition:opacity 0.8s;-webkit-transition:opacity 0.8s;\n"; 
echo "	    		}\n"; 
echo "	    		#logo:hover\n"; 
echo "	    		{\n"; 
echo "	    			opacity:1;transition:opacity 0.8s;-moz-transition:opacity 0.8s;-webkit-transition:opacity 0.8s;\n"; 
echo "	    		}\n"; 
echo "	    		.number\n"; 
echo "	    		{\n"; 
echo "	    			color:#00aeef;\n"; 
echo "	    			padding:1px 8px;\n"; 
echo "	    			border:3px solid #00aeef;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			font-size:18pt;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			text-align:center;\n"; 
echo "	    		}\n"; 
echo "	    		\n"; 
echo "	    		.figure\n"; 
echo "	    		{\n"; 
echo "	    			padding: 0px;\n"; 
echo "	    			vertical-align: middle;\n"; 
echo "	    		}\n"; 
echo "	    		#remark{\n"; 
echo "	    			position: absolute;\n"; 
echo "	    			margin:30px 0px 0px 130px;\n"; 
echo "	    		}\n"; 
echo "	    		\n"; 
echo "	    		.table\n"; 
echo "	    		{\n"; 
echo "	    			margin:5px 0px 5px 115px;\n"; 
echo "	    			padding:10px;\n"; 
echo "	    			border:0px solid #cdcdcd;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    		}\n"; 
echo "	    		.table_main\n"; 
echo "	    		{\n"; 
echo "	    			margin:0px auto;\n"; 
echo "	    			padding:0px 20px;\n"; 
echo "	    			border:0px solid #cdcdcd;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    		}\n"; 
echo "	    		.text\n"; 
echo "	    		{\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:13pt;\n"; 
echo "	    			color:#333;\n"; 
echo "	    			vertical-align: middle;\n"; 
echo "	    		}\n"; 
echo "	    		a.plus\n"; 
echo "	    		{\n"; 
echo "	    			color:#333;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:13pt;\n"; 
echo "	    			font-weight: normal;\n"; 
echo "	    			background:url('http://gmtest.ru/wp-content/themes/mio/images/nav_bg.png') repeat-x scroll top center #f0f0f0;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			border:1px solid #cdcdcd;\n"; 
echo "	    			padding: 2px 8px 2px 7px;\n"; 
echo "	    			vertical-align:middle;\n"; 
echo "	    			text-shadow: 1px 1px #fff;\n"; 
echo "	    			margin: 0px -50px 0px 61px\n"; 
echo "	    		}\n"; 
echo "	    		a.plus:hover\n"; 
echo "	    		{\n"; 
echo "	    			color:#0c9adc;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:13pt;\n"; 
echo "	    			border:1px solid #0c9adc;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    		}\n"; 
echo "	    		.tip\n"; 
echo "	    		{\n"; 
echo "	    		display: inline-block;\n"; 
echo "	    		position: relative;\n"; 
echo "	    		}\n"; 
echo "	    		.tip:hover::after\n"; 
echo "	    		{\n"; 
echo "	    		content: attr(data-title);\n"; 
echo "	    		margin: -85px auto 0px -210px;\n"; 
echo "	    		background: #fbf69a;\n"; 
echo "	    		font-family: Arial;\n"; 
echo "	    		font-size: 12pt;\n"; 
echo "	    		border-radius: 4px;\n"; 
echo "	    		color: #333;\n"; 
echo "	    		width: 260px;\n"; 
echo "	    		padding: 6px;\n"; 
echo "	    		position: absolute;\n"; 
echo "	    		text-align: left;\n"; 
echo "	    		z-index: 0;\n"; 
echo "	    		box-shadow:0px 1px 2px rgba(0, 0, 0, 0.4);\n"; 
echo "	    		-moz-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.4);\n"; 
echo "	    		-webkit-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.4);\n"; 
echo "	    		}\n"; 
echo "	    		.tip:hover::before\n"; 
echo "	    		{\n"; 
echo "	    		//content: \"\2666\";\n"; 
echo "	    		//color:#fbf69a ;\n"; 
echo "	    		//font-size: 30px;\n"; 
echo "	    		//line-height: 30px;\n"; 
echo "	    		//clip:rect(15px, 30px, 30px, 0px);\n"; 
echo "	    		margin: -34px 0px 0px 66px;\n"; 
echo "	    		border: solid;\n"; 
echo "	    		border-color: #fbf69a transparent;\n"; 
echo "	    		border-width: 13px 10px 0 10px;\n"; 
echo "	    		content: \"\";\n"; 
echo "	    		position: absolute;\n"; 
echo "	    		margin: -20px 0px 0px 64px;\n"; 
echo "	    		z-index:1;\n"; 
echo "	    		}\n"; 
echo "	    		.play\n"; 
echo "	    		{\n"; 
echo "	    			opacity:0.8;transition:opacity 0.8s;-moz-transition:opacity 0.8s;-webkit-transition:opacity 0.8s;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			border: none;\n"; 
echo "	    			margin: 25px 0px 5px 0px;\n"; 
echo "	    			box-shadow: 0px 1px 2px #ed1c24;\n"; 
echo "	    			-moz-box-shadow: 0px 1px 2px #ed1c24;\n"; 
echo "	    			-webkit-box-shadow: 0px 1px 2px #ed1c24;\n"; 
echo "	    			vertical-align: middle;\n"; 
echo "	    			outline: none;\n"; 
echo "	    			height:61px;\n"; 
echo "	    			width: 61px;\n"; 
echo "	    			cursor: pointer;\n"; 
echo "	    			background: url('http://gmtest.ru/wp-content/uploads/2013/11/play.png') no-repeat;\n"; 
echo "	    			background-position: center;\n"; 
echo "	    		}\n"; 
echo "	    		.play:hover\n"; 
echo "	    		{\n"; 
echo "	    			opacity:1;transition:opacity 0.8s;-moz-transition:opacity 0.8s;-webkit-transition:opacity 0.8s;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			border: none;\n"; 
echo "	    			box-shadow: 0px 1px 2px #0c9adc;\n"; 
echo "	    			-moz-box-shadow: 0px 1px 2px #0c9adc;\n"; 
echo "	    			-webkit-box-shadow: 0px 1px 2px #0c9adc;\n"; 
echo "	    			background: url('http://gmtest.ru/wp-content/uploads/2013/11/play_hover.png') no-repeat;\n"; 
echo "	    			background-position: center;\n"; 
echo "	    		}\n"; 
echo "	    		a.button\n"; 
echo "	    		{\n"; 
echo "	    			color:#333;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:12pt;\n"; 
echo "	    			display: -moz-inline-stack;\n"; 
echo "	    			display: inline-block;\n"; 
echo "	    			width: 128px; \n"; 
echo "	    			background:url('http://gmtest.ru/wp-content/themes/mio/images/nav_bg.png') repeat-x scroll top center #f0f0f0;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			border:2px solid #cdcdcd;\n"; 
echo "	    			vertical-align:middle;\n"; 
echo "	    			text-shadow: 1px 1px #fff;\n"; 
echo "	    			height:30px;\n"; 
echo "	    			line-height: 30px;\n"; 
echo "	    			vertical-align: middle;\n"; 
echo "	    			text-align: center;\n"; 
echo "	    			cursor: pointer;\n"; 
echo "	    		}\n"; 
echo "	    		a.button:hover\n"; 
echo "	    		{\n"; 
echo "	    			-moz-transition: color 1.7s ease;\n"; 
echo "	    			    -webkit-transition: color 1.7s ease;\n"; 
echo "	    			    -o-transition: color 1.7s ease;\n"; 
echo "	    			    transition: color 1.7s ease;\n"; 
echo "	    			color:#0c9adc;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:12pt;\n"; 
echo "	    			border:2px solid #0c9adc;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    		}\n"; 
echo "	    		a.button:active,\n"; 
echo "	    		a.button:focus\n"; 
echo "	    		{\n"; 
echo "	    			background: -moz-linear-gradient(top, rgba(180,180,180,1) 0%, rgba(195,195,195,0.4) 25%, rgba(240,240,240,1) 100%);\n"; 
echo "	    			background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(180,180,180,1)), color-stop(25%,rgba(195,195,195,0.4)), color-stop(100%,rgba(240,240,240,1)));\n"; 
echo "	    			background: -webkit-linear-gradient(top, rgba(180,180,180,1) 0%,rgba(195,195,195,0.4) 25%,rgba(240,240,240,1) 100%);\n"; 
echo "	    			background: -o-linear-gradient(top, rgba(180,180,180,1) 0%,rgba(195,195,195,0.4) 25%,rgba(240,240,240,1) 100%);\n"; 
echo "	    			background: -ms-linear-gradient(top, rgba(180,180,180,1) 0%,rgba(195,195,195,0.4) 25%,rgba(240,240,240,1) 100%);\n"; 
echo "	    			background: linear-gradient(to bottom, rgba(180,180,180,1) 0%,rgba(195,195,195,0.4) 25%,rgba(240,240,240,1) 100%);\n"; 
echo "	    			border:2px solid #cdcdcd !important;\n"; 
echo "	    			color:#333;\n"; 
echo "	    			outline: none;\n"; 
echo "	    		}\n"; 
echo "	    		#labValue\n"; 
echo "	    		{\n"; 
echo "	    			text-align:center;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:13pt;\n"; 
echo "	    			color:#333;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			border:1px solid #cdcdcd;\n"; 
echo "	    			padding:2px;\n"; 
echo "	    			vertical-align: middle;\n"; 
echo "	    			height:25px;\n"; 
echo "	    			transition: all 0.5s ease;\n"; 
echo "	    			-webkit-transition: all 0.5s ease;\n"; 
echo "	    			-moz-transition: all 0.5s ease;\n"; 
echo "	    		}\n"; 
echo "	    		#labValue:hover\n"; 
echo "	    		{\n"; 
echo "	    			text-align:center;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:14pt;\n"; 
echo "	    			color:#333;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			border:2px solid #0c9adc;\n"; 
echo "	    			padding:2px;\n"; 
echo "	    			box-shadow:0 0 3px #0c9adc;\n"; 
echo "	    			-moz-box-shadow: 0 0 3px #0c9adc;\n"; 
echo "	    			-webkit-box-shadow: 0 0 3px #0c9adc;\n"; 
echo "	    			vertical-align: middle;\n"; 
echo "	    			transition: all 0.5s ease;\n"; 
echo "	    			-webkit-transition: all 0.5s ease;\n"; 
echo "	    			-moz-transition: all 0.5s ease;\n"; 
echo "	    		}\n"; 
echo "	    		#labValue:active,\n"; 
echo "	    		#labValue:focus\n"; 
echo "	    		{\n"; 
echo "	    			text-align:center;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:14pt;\n"; 
echo "	    			color:#333;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			border:2px solid #0c9adc;\n"; 
echo "	    			outline: none;\n"; 
echo "	    			//outline: 5px auto -webkit-focus-ring-color;\n"; 
echo "	    			//outline-offset: -3px;\n"; 
echo "	    			//outline-color: #00aeef;\n"; 
echo "	    			padding:2px;\n"; 
echo "	    			vertical-align: middle;\n"; 
echo "	    			box-shadow:0 0 3px #0c9adc;\n"; 
echo "	    			-moz-box-shadow: 0 0 3px #0c9adc;\n"; 
echo "	    			-webkit-box-shadow: 0 0 3px #0c9adc;\n"; 
echo "	    		}\n"; 
echo "	    		#expValue\n"; 
echo "	    		{\n"; 
echo "	    			text-align:center;\n"; 
echo "	    			height:25px;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:13pt;\n"; 
echo "	    			color:#333;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			border:1px solid #cdcdcd;\n"; 
echo "	    			padding:2px;\n"; 
echo "	    			vertical-align: middle;\n"; 
echo "	    			transition: all 0.5s ease;\n"; 
echo "	    			-webkit-transition: all 0.5s ease;\n"; 
echo "	    			-moz-transition: all 0.5s ease;\n"; 
echo "	    		}\n"; 
echo "	    		#expValue:active,\n"; 
echo "	    		#expValue:focus\n"; 
echo "	    		{\n"; 
echo "	    			text-align:center;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:14pt;\n"; 
echo "	    			color:#333;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			border:2px solid #0c9adc;\n"; 
echo "	    			outline: none;\n"; 
echo "	    			//outline: 5px auto -webkit-focus-ring-color;\n"; 
echo "	    			//outline-offset: -3px;\n"; 
echo "	    			//outline-color: #00aeef;\n"; 
echo "	    			padding:2px;\n"; 
echo "	    			vertical-align: middle;\n"; 
echo "	    			box-shadow:0 0 3px #0c9adc;\n"; 
echo "	    			-moz-box-shadow: 0 0 3px #0c9adc;\n"; 
echo "	    			-webkit-box-shadow: 0 0 3px #0c9adc;\n"; 
echo "	    		}\n"; 
echo "	    		#expValue:hover\n"; 
echo "	    		{\n"; 
echo "	    			text-align:center;\n"; 
echo "	    			font-family:Arial;\n"; 
echo "	    			font-size:14pt;\n"; 
echo "	    			color:#333;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			border:2px solid #0c9adc;\n"; 
echo "	    			padding:2px;\n"; 
echo "	    			box-shadow:0 0 3px #0c9adc;\n"; 
echo "	    			-moz-box-shadow: 0 0 3px #0c9adc;\n"; 
echo "	    			-webkit-box-shadow: 0 0 3px #0c9adc;\n"; 
echo "	    			vertical-align: middle;\n"; 
echo "	    			transition: all 0.5s ease;\n"; 
echo "	    			-webkit-transition: all 0.5s ease;\n"; 
echo "	    			-moz-transition: all 0.5s ease;\n"; 
echo "	    		}\n"; 
echo "	    		iframe\n"; 
echo "	    		{\n"; 
echo "	    			margin-top:10px;\n"; 
echo "	    			width:750px;\n"; 
echo "	    			height:500px;\n"; 
echo "	    			border-top:1px solid #cdcdcd;\n"; 
echo "	    			border-radius:4px;\n"; 
echo "	    			padding:5px;\n"; 
echo "	    			box-shadow:0px 1px 2px rgba(0, 0, 0, 0.4);\n"; 
echo "	    			-moz-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.4);\n"; 
echo "	    			-webkit-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.4);\n"; 
echo "	    		}\n"; 
echo "	    		.spoiler\n"; 
echo "	    		{\n"; 
echo "	    			margin:0px;\n"; 
echo "	    		}\n"; 
echo "	    		.select\n"; 
echo "	    		{\n"; 
echo "	    			vertical-align:middle;\n"; 
echo "	    			background:url('http://gmtest.ru/wp-content/themes/mio/images/nav_bg.png') repeat-x scroll top center #f0f0f0;\n"; 
echo "	    			border: 1px solid #cdcdcd;\n"; 
echo "	    			border-radius: 4px;\n"; 
echo "	    			font-family: Arial;\n"; 
echo "	    			font-size: 13pt;\n"; 
echo "	    			padding: 5px;\n"; 
echo "	    			position: relative;\n"; 
echo "	    			text-align: left;\n"; 
echo "	    		}\n"; 
echo "	    		.select:active,\n"; 
echo "	    		.select:focus\n"; 
echo "	    		{\n"; 
echo "	    			vertical-align:middle;\n"; 
echo "	    			background:url('http://gmtest.ru/wp-content/themes/mio/images/nav_bg.png') repeat-x scroll top center #f0f0f0;\n"; 
echo "	    			border-radius: 4px;\n"; 
echo "	    			font-family: Arial;\n"; 
echo "	    			font-size: 12pt;\n"; 
echo "	    			padding: 5px;\n"; 
echo "	    			position: relative;\n"; 
echo "	    			text-align: left;\n"; 
echo "	    			border:1px solid transparent;\n"; 
echo "	    			outline: 5px auto -webkit-focus-ring-color;\n"; 
echo "	    			outline-offset: -3px;\n"; 
echo "	    			outline-color: #00aeef;\n"; 
echo "	    		}		\n"; 
echo "	    #print_button, .play, #remark, #footer, .plus, .tip, .play, .play1, iframe {display: none;}\n"; 
echo "	    }\n"; 
echo "	    @media screen\n"; 
echo "	    {\n"; 
echo "	    .noselect {\n"; 
echo "	        -moz-user-select: none;\n"; 
echo "	        -webkit-user-select: none;\n"; 
echo "	        -ms-user-select: none;\n"; 
echo "	        -o-user-select: none;\n"; 
echo "	        user-select: none;\n"; 
echo "	    }	    \n"; 
echo "		a\n"; 
echo "		{\n"; 
echo "			text-align:justify;\n"; 
echo "			font-family:Arial;\n"; 
echo "			margin-left: 12px;\n"; 
echo "			font-size:10pt;\n"; 
echo "			color:#343593;\n"; 
echo "			text-decoration: none;\n"; 
echo "			font-weight: normal;\n"; 
echo "		}\n"; 
echo "		li{\n"; 
echo "			margin-bottom: 5px;\n"; 
echo "		}\n"; 
echo "		#visible\n"; 
echo "		{\n"; 
echo "			display: none;\n"; 
echo "		}\n"; 
echo "		#visible1\n"; 
echo "		{\n"; 
echo "			opacity: 0.5;\n"; 
echo "			transition: all 0.2s ease;\n"; 
echo "			-webkit-transition: all 0.2s ease;\n"; 
echo "			-moz-transition: all 0.2s ease;\n"; 
echo "		}\n"; 
echo "		#visible1:hover\n"; 
echo "		{\n"; 
echo "			opacity: 1;\n"; 
echo "			transition: all 0.2s ease;\n"; 
echo "			-webkit-transition: all 0.2s ease;\n"; 
echo "			-moz-transition: all 0.2s ease;\n"; 
echo "		}\n"; 
echo "		.header\n"; 
echo "		{\n"; 
echo "			color:#333;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:9pt;\n"; 
echo "			width: 860px; \n"; 
echo "			background:url('http://gmtest.ru/wp-content/themes/mio/images/nav_bg.png') repeat-x scroll top center #f0f0f0;\n"; 
echo "			border-radius:4px;\n"; 
echo "			margin: 5px 0px 25px 20px;\n"; 
echo "			padding: 0px 0px 0px 85px;\n"; 
echo "			border:1px solid #bdbdbd;\n"; 
echo "			vertical-align:middle;\n"; 
echo "			text-shadow: 1px 1px #fff;\n"; 
echo "			height:45px;\n"; 
echo "			text-align: left;\n"; 
echo "		}\n"; 
echo "		.link\n"; 
echo "		{\n"; 
echo "			text-align:justify;\n"; 
echo "			font-family:Arial;\n"; 
echo "			margin-left: 0px;\n"; 
echo "			font-size:10pt;\n"; 
echo "			color:#343593;\n"; 
echo "			text-decoration: underline;\n"; 
echo "			font-weight: normal;\n"; 
echo "		}\n"; 
echo "		.link:hover\n"; 
echo "		{\n"; 
echo "			text-align:justify;\n"; 
echo "			font-family:Arial;\n"; 
echo "			margin-left: 0px;\n"; 
echo "			font-size:10pt;\n"; 
echo "			color:#0c9adc;\n"; 
echo "			text-decoration: none;\n"; 
echo "			font-weight: normal;\n"; 
echo "		}\n"; 
echo "		p\n"; 
echo "		{\n"; 
echo "			text-align:center;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:12pt;\n"; 
echo "			color:#333;\n"; 
echo "		}\n"; 
echo "		h1\n"; 
echo "		{\n"; 
echo "			text-align:center;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:12pt;\n"; 
echo "			color:#333;\n"; 
echo "			font-weight: normal;\n"; 
echo "		}\n"; 
echo "		.rt_none \n"; 
echo "		{\n"; 
echo "			display: none;\n"; 
echo "			border-radius:4px;\n"; 
echo "		}\n"; 
echo "\n"; 
echo "		.rt_gray \n"; 
echo "		{\n"; 
echo "			margin:20px auto;\n"; 
echo "			width:860px;\n"; 
echo "			margin-top: 5px;\n"; 
echo "			border-radius:4px;\n"; 
echo "			border-collapse:collapse;		\n"; 
echo "			border: 1px solid #b9b9b9;\n"; 
echo "			background-color: #e1e1e1;\n"; 
echo "			display: block;\n"; 
echo "		}\n"; 
echo "		.rt_gray td { border: 1px solid #b9b9b9; padding: 5px;border-radius:4px;	 }\n"; 
echo "		.rt_green \n"; 
echo "		{\n"; 
echo "			margin:20px auto;\n"; 
echo "			width:860px;\n"; 
echo "			margin-top: 5px;\n"; 
echo "			border-radius:4px;\n"; 
echo "			border-collapse:collapse;		\n"; 
echo "			border: 1px solid #00af5a;\n"; 
echo "			background-color: #cef8ce;\n"; 
echo "			display: block;\n"; 
echo "		}\n"; 
echo "		.rt_green td { border: 1px solid #00af5a; padding: 5px;border-radius:4px;	 }\n"; 
echo "		.rt_green #reportTitle {text-align: center; font-family:Arial;font-size: 14pt; color: #188338; }\n"; 
echo "		\n"; 
echo "		.rt_red\n"; 
echo "		{\n"; 
echo "			margin:20px auto;\n"; 
echo "			width:860px;\n"; 
echo "			margin-top: 5px;\n"; 
echo "			border-collapse:collapse;	\n"; 
echo "			border-radius:4px;	\n"; 
echo "			border: 1px solid #ed1c24;\n"; 
echo "			background-color: #f7e2e2;\n"; 
echo "			display: block;			\n"; 
echo "		}\n"; 
echo "		.rt_red td { border: 1px solid #ed1c24; padding: 5px;border-radius:4px;}\n"; 
echo "		.rt_red #reportTitle {text-align: center; font-family:Arial; font-size: 14pt; color: #ed1c24; }\n"; 
echo "		#testReport {font-family:Arial; font-size:12pt; text-align:center; color:#333;}\n"; 
echo "		.report_note \n"; 
echo "		{\n"; 
echo "			border-collapse:collapse;			\n"; 
echo "			border: 0;			\n"; 
echo "			background: #fff;\n"; 
echo "			border-radius:4px	;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:12pt;\n"; 
echo "			color:#333;\n"; 
echo "			text-align:justify;\n"; 
echo "			padding:5px;\n"; 
echo "		}\n"; 
echo "		.report_note td {border: 0;}\n"; 
echo "		\n"; 
echo "		.cube {border: 2px solid #ed1c24; font-size: 14pt; padding: 2px; margin: 0px 4px 0px 0px; font-family:Arial; border-radius:4px;}\n"; 
echo "		\n"; 
echo "		#Anal {text-align: center;font-family:Arial;font-size:14pt;}\n"; 
echo "		#Anal1 {text-align: center;font-family:Arial;font-size:14pt;}\n"; 
echo "		#yourResult {text-align: center;font-family:Arial;font-size:12pt; vertical-align: middle;}\n"; 
echo "		#yourRange {text-align: center;font-family:Arial;font-size:12pt;vertical-align: middle;}\n"; 
echo "		\n"; 
echo "		#error1 \n"; 
echo "		{\n"; 
echo "			color:#ed1c24; display: none; margin:20px auto; border: 1px solid red;\n"; 
echo "			border-radius:4px; background-color:#f7e2e2; text-align:center; width:600px;font-family:Arial;	font-size:14pt;\n"; 
echo "		}\n"; 
echo "		#error2 \n"; 
echo "		{\n"; 
echo "			color:#ed1c24; display: none; margin:20px auto; border: 1px solid red;\n"; 
echo "			border-radius:4px; background-color:#f7e2e2; text-align:center; width:600px;font-family:Arial;	font-size:14pt;\n"; 
echo "		}\n"; 
echo "		#error3 \n"; 
echo "		{\n"; 
echo "			color:#ed1c24; display: none; margin:20px auto; border: 1px solid red;\n"; 
echo "			border-radius:4px; background-color:#f7e2e2; text-align:center; width:600px;font-family:Arial;	font-size:14pt;\n"; 
echo "		}\n"; 
echo "		#error4 \n"; 
echo "		{\n"; 
echo "			color:#333; display: none; font-family:Arial; font-size:14pt; text-align:center;\n"; 
echo "		}\n"; 
echo "		#error5 \n"; 
echo "		{\n"; 
echo "			color:#333; display: none; font-family:Arial; font-size:14pt; text-align:center;\n"; 
echo "		}\n"; 
echo "		#error6 \n"; 
echo "		{\n"; 
echo "				color:#ed1c24; display: none; margin:20px auto; border: 1px solid red;\n"; 
echo "				border-radius:4px; background-color:#f7e2e2; text-align:center; width:600px;font-family:Arial;	font-size:14pt;\n"; 
echo "		}\n"; 
echo "		#error7 \n"; 
echo "		{\n"; 
echo "				color:#ed1c24; display: none; margin:20px auto; border: 1px solid red;\n"; 
echo "				border-radius:4px; background-color:#f7e2e2; text-align:center; width:600px;font-family:Arial;	font-size:14pt;\n"; 
echo "		}\n"; 
echo "		#error8 \n"; 
echo "		{\n"; 
echo "			color:#333; display: none; font-family:Arial; font-size:14pt;\n"; 
echo "		}\n"; 
echo "		#printer \n"; 
echo "		{\n"; 
echo "			display: none;\n"; 
echo "		}\n"; 
echo "		#logo\n"; 
echo "		{\n"; 
echo "			opacity:1;transition:opacity 0.8s;-moz-transition:opacity 0.8s;-webkit-transition:opacity 0.8s;\n"; 
echo "		}\n"; 
echo "		#logo:hover\n"; 
echo "		{\n"; 
echo "			opacity:1;transition:opacity 0.8s;-moz-transition:opacity 0.8s;-webkit-transition:opacity 0.8s;\n"; 
echo "		}\n"; 
echo "		.number\n"; 
echo "		{\n"; 
echo "			color:#00aeef;\n"; 
echo "			padding:1px 8px;\n"; 
echo "			border:3px solid #00aeef;\n"; 
echo "			border-radius:4px;\n"; 
echo "			font-size:18pt;\n"; 
echo "			font-family:Arial\n"; 
echo "			text-align:center;\n"; 
echo "		}\n"; 
echo "		\n"; 
echo "		.figure\n"; 
echo "		{\n"; 
echo "			padding: 0px;\n"; 
echo "			vertical-align: middle;\n"; 
echo "		}\n"; 
echo "		#remark{\n"; 
echo "			position: absolute;\n"; 
echo "			margin:30px 0px 0px 125px;\n"; 
echo "		}\n"; 
echo "		.body\n"; 
echo "		{\n"; 
echo "			width:900px;\n"; 
echo "			margin:10px auto;\n"; 
echo "		}\n"; 
echo "		.container\n"; 
echo "		{\n"; 
echo "			width:900px;\n"; 
echo "			margin:10px auto;\n"; 
echo "			border-radius:4px;\n"; 
echo "			border-top:1px solid #cdcdcd;\n"; 
echo "			box-shadow:0px 1px 2px rgba(0, 0, 0, 0.4);\n"; 
echo "			-moz-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.4);\n"; 
echo "			-webkit-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.4);\n"; 
echo "		}\n"; 
echo "		.table\n"; 
echo "		{\n"; 
echo "			margin:5px 0px 5px 115px;\n"; 
echo "			padding:10px;\n"; 
echo "			border:0px solid #cdcdcd;\n"; 
echo "			border-radius:4px;\n"; 
echo "		}\n"; 
echo "		.table_main\n"; 
echo "		{\n"; 
echo "			margin:0px auto;\n"; 
echo "			padding:0px 20px;\n"; 
echo "			border:0px solid #cdcdcd;\n"; 
echo "			border-radius:4px;\n"; 
echo "		}\n"; 
echo "		.text\n"; 
echo "		{\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:13pt;\n"; 
echo "			color:#333;\n"; 
echo "			vertical-align: middle;\n"; 
echo "		}\n"; 
echo "		a.plus\n"; 
echo "		{\n"; 
echo "			color:#8f8f8f;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:15pt;\n"; 
echo "			font-weight: normal;\n"; 
echo "			display: -moz-inline-stack;\n"; 
echo "			display: inline-block;\n"; 
echo "			background:url('http://gmtest.ru/wp-content/themes/mio/images/nav_bg.png') repeat-x scroll top center #f0f0f0;\n"; 
echo "			height: 30px;\n"; 
echo "			width: 30px;\n"; 
echo "			line-height: 30px;\n"; 
echo "			border-radius:4px;\n"; 
echo "			border:1px solid #cdcdcd;\n"; 
echo "			text-align: center;\n"; 
echo "			vertical-align:middle;\n"; 
echo "			text-shadow: 1px 1px #fff;\n"; 
echo "			margin: 0px -27px 0px 5px;\n"; 
echo "			transition: all 0.5s ease;\n"; 
echo "			-webkit-transition: all 0.5s ease;\n"; 
echo "			-moz-transition: all 0.5s ease;\n"; 
echo "		}\n"; 
echo "		a.plus:hover\n"; 
echo "		{\n"; 
echo "			color:#0c9adc;\n"; 
echo "			font-family:Arial;\n"; 
echo "			border:1px solid #0c9adc;\n"; 
echo "			border-radius:4px;\n"; 
echo "			transition: all 0.5s ease;\n"; 
echo "			-webkit-transition: all 0.5s ease;\n"; 
echo "			-moz-transition: all 0.5s ease;\n"; 
echo "			box-shadow:0 0 3px #0c9adc;\n"; 
echo "			-moz-box-shadow: 0 0 3px #0c9adc;\n"; 
echo "			-webkit-box-shadow: 0 0 3px #0c9adc;\n"; 
echo "		}\n"; 
echo "		a.plus:active,\n"; 
echo "		a.plus:focus\n"; 
echo "		{\n"; 
echo "			box-shadow: inset 0px 1px 2px 0px #333 !important;\n"; 
echo "			border:1px solid #cdcdcd !important;\n"; 
echo "			color:#8f8f8f;\n"; 
echo "			outline: none;\n"; 
echo "			transition: all 0s ease-out;\n"; 
echo "			-webkit-transition: all 0s ease-out;\n"; 
echo "			-moz-transition: all 0s ease-out;\n"; 
echo "			box-shadow:none;\n"; 
echo "			-moz-box-shadow: none;\n"; 
echo "			-webkit-box-shadow: none;\n"; 
echo "		}\n"; 
echo "		.tip:hover::after\n"; 
echo "		{\n"; 
echo "		content: attr(data-title);\n"; 
echo "		margin: -87px auto 0px -210px;\n"; 
echo "		background: #fbf69a;\n"; 
echo "		font-family: Arial;\n"; 
echo "		font-size: 12pt;\n"; 
echo "		border-radius: 4px;\n"; 
echo "		color: #333;\n"; 
echo "		width: 260px;\n"; 
echo "		padding: 6px;\n"; 
echo "		position: absolute;\n"; 
echo "		text-align: left;\n"; 
echo "		z-index: 0;\n"; 
echo "		border: 1px solid #cdcdcd;\n"; 
echo "		}\n"; 
echo "		.tip:hover::before\n"; 
echo "		{\n"; 
echo "		//content: \"\2666\";\n"; 
echo "		//color:#fbf69a ;\n"; 
echo "		//font-size: 30px;\n"; 
echo "		//line-height: 30px;\n"; 
echo "		//clip:rect(15px, 30px, 30px, 0px);\n"; 
echo "		//margin: -34px 0px 0px 66px;\n"; 
echo "		border: solid;\n"; 
echo "		border-color: #fbf69a transparent;\n"; 
echo "		border-width: 13px 10px 0 10px;\n"; 
echo "		content: \"\";\n"; 
echo "		position: absolute;\n"; 
echo "		margin: -20px 0px 0px 10px;\n"; 
echo "		transition: background 1s ease;\n"; 
echo "		-webkit-transition:background 1s ease;\n"; 
echo "		-moz-transition: background 1s ease;\n"; 
echo "		z-index:1;\n"; 
echo "		}\n"; 
echo "		.play\n"; 
echo "		{\n"; 
echo "			border-radius:4px;\n"; 
echo "			border: none;\n"; 
echo "			margin: 17px 0px 0px 196px;\n"; 
echo "			vertical-align: middle;\n"; 
echo "			outline: none;\n"; 
echo "			height:66px;\n"; 
echo "			width: 289px;\n"; 
echo "			cursor: pointer;\n"; 
echo "			background: url('http://gmtest.ru/wp-content/uploads/2013/11/remark_new.png') no-repeat;\n"; 
echo "		}\n"; 
echo "		.play:active,\n"; 
echo "		.play:focus\n"; 
echo "		{\n"; 
echo "			border-radius:4px;\n"; 
echo "			border: none;\n"; 
echo "			cursor: pointer;\n"; 
echo "			background-position: 0 -66px;\n"; 
echo "		}\n"; 
echo "		.play:hover\n"; 
echo "		{\n"; 
echo "			border-radius:4px;\n"; 
echo "			border: none;\n"; 
echo "			cursor: pointer;\n"; 
echo "			background-position: 0 -66px;\n"; 
echo "		}\n"; 
echo "		.play1\n"; 
echo "		{\n"; 
echo "			border-radius:4px;\n"; 
echo "			border: none;\n"; 
echo "			margin: 17px 0px 0px 196px;\n"; 
echo "			vertical-align: middle;\n"; 
echo "			outline: none;\n"; 
echo "			height:66px;\n"; 
echo "			width: 289px;\n"; 
echo "			cursor: pointer;\n"; 
echo "			background: url('http://gmtest.ru/wp-content/uploads/2013/11/remark_new.png') no-repeat;\n"; 
echo "			background-position: 0 -132px;\n"; 
echo "		}\n"; 
echo "		.play1:active,\n"; 
echo "		.play1:focus\n"; 
echo "		{\n"; 
echo "			border-radius:4px;\n"; 
echo "			border: none;\n"; 
echo "			cursor: pointer;\n"; 
echo "			background-position: 0 -132px;\n"; 
echo "		}\n"; 
echo "		.play1:hover\n"; 
echo "		{\n"; 
echo "			border-radius:4px;\n"; 
echo "			border: none;\n"; 
echo "			cursor: pointer;\n"; 
echo "			background-position: 0 -66px;\n"; 
echo "		}\n"; 
echo "		a.button\n"; 
echo "		{\n"; 
echo "			color:#333;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:13pt;\n"; 
echo "			display: -moz-inline-stack;\n"; 
echo "			display: inline-block;\n"; 
echo "			width: 128px; \n"; 
echo "			background:url('http://gmtest.ru/wp-content/themes/mio/images/nav_bg.png') repeat-x scroll top center #f0f0f0;\n"; 
echo "			border-radius:4px;\n"; 
echo "			border:1px solid #cdcdcd;\n"; 
echo "			vertical-align:middle;\n"; 
echo "			text-shadow: 1px 1px #fff;\n"; 
echo "			height:30px;\n"; 
echo "			line-height: 30px;\n"; 
echo "			vertical-align: middle;\n"; 
echo "			text-align: center;\n"; 
echo "			cursor: pointer;\n"; 
echo "			transition: all 0.5s ease;\n"; 
echo "			-webkit-transition: all 0.5s ease;\n"; 
echo "			-moz-transition: all 0.5s ease;\n"; 
echo "		}\n"; 
echo "		a.button:hover\n"; 
echo "		{\n"; 
echo "			color:#0c9adc;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:13pt;\n"; 
echo "			border:1px solid #0c9adc;\n"; 
echo "			border-radius:4px;\n"; 
echo "			transition: all 0.5s ease;\n"; 
echo "			-webkit-transition: all 0.5s ease;\n"; 
echo "			-moz-transition: all 0.5s ease;\n"; 
echo "			box-shadow:0 0 3px #0c9adc;\n"; 
echo "			-moz-box-shadow: 0 0 3px #0c9adc;\n"; 
echo "			-webkit-box-shadow: 0 0 3px #0c9adc;\n"; 
echo "		}\n"; 
echo "		a.button:active,\n"; 
echo "		a.button:focus\n"; 
echo "		{\n"; 
echo "			/*background: -moz-linear-gradient(top, rgba(180,180,180,1) 0%, rgba(195,195,195,0.4) 25%, rgba(240,240,240,1) 100%);\n"; 
echo "			background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(180,180,180,1)), color-stop(25%,rgba(195,195,195,0.4)), color-stop(100%,rgba(240,240,240,1)));\n"; 
echo "			background: -webkit-linear-gradient(top, rgba(180,180,180,1) 0%,rgba(195,195,195,0.4) 25%,rgba(240,240,240,1) 100%);\n"; 
echo "			background: -o-linear-gradient(top, rgba(180,180,180,1) 0%,rgba(195,195,195,0.4) 25%,rgba(240,240,240,1) 100%);\n"; 
echo "			background: -ms-linear-gradient(top, rgba(180,180,180,1) 0%,rgba(195,195,195,0.4) 25%,rgba(240,240,240,1) 100%);\n"; 
echo "			background: linear-gradient(to bottom, rgba(180,180,180,1) 0%,rgba(195,195,195,0.4) 25%,rgba(240,240,240,1) 100%);*/\n"; 
echo "			box-shadow: inset 0px 1px 2px 0px #333 !important;\n"; 
echo "			border:1px solid #cdcdcd !important;\n"; 
echo "			color:#333;\n"; 
echo "			outline: none;\n"; 
echo "			transition: all 0s ease-out;\n"; 
echo "			-webkit-transition: all 0s ease-out;\n"; 
echo "			-moz-transition: all 0s ease-out;\n"; 
echo "			box-shadow:none;\n"; 
echo "			-moz-box-shadow: none;\n"; 
echo "			-webkit-box-shadow: none;\n"; 
echo "		}\n"; 
echo "		#labValue\n"; 
echo "		{\n"; 
echo "			text-align:center;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:13pt;\n"; 
echo "			color:#0c9adc;\n"; 
echo "			border-radius:4px;\n"; 
echo "			border:1px solid #cdcdcd;\n"; 
echo "			padding:2px;\n"; 
echo "			vertical-align: middle;\n"; 
echo "			height:25px;\n"; 
echo "			transition: all 0.5s ease;\n"; 
echo "			-webkit-transition: all 0.5s ease;\n"; 
echo "			-moz-transition: all 0.5s ease;\n"; 
echo "		}\n"; 
echo "		#labValue:hover\n"; 
echo "		{\n"; 
echo "			text-align:center;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:13pt;\n"; 
echo "			color:#333;\n"; 
echo "			border-radius:4px;\n"; 
echo "			border:1px solid #0c9adc !important;\n"; 
echo "			padding:2px;\n"; 
echo "			box-shadow:0 0 3px #0c9adc !important;\n"; 
echo "			-moz-box-shadow: 0 0 3px #0c9adc !important;\n"; 
echo "			-webkit-box-shadow: 0 0 3px #0c9adc !important;\n"; 
echo "			vertical-align: middle;\n"; 
echo "			transition: all 0.5s ease;\n"; 
echo "			-webkit-transition: all 0.5s ease;\n"; 
echo "			-moz-transition: all 0.5s ease;\n"; 
echo "		}\n"; 
echo "		#labValue:active,\n"; 
echo "		#labValue:focus\n"; 
echo "		{\n"; 
echo "			text-align:center;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:13pt;\n"; 
echo "			color:#333;\n"; 
echo "			border-radius:4px;\n"; 
echo "			border:1px solid #0c9adc !important;\n"; 
echo "			outline: none;\n"; 
echo "			//outline: 5px auto -webkit-focus-ring-color;\n"; 
echo "			//outline-offset: -3px;\n"; 
echo "			//outline-color: #00aeef;\n"; 
echo "			padding:2px;\n"; 
echo "			vertical-align: middle;\n"; 
echo "			box-shadow:0 0 3px #0c9adc !important;\n"; 
echo "			-moz-box-shadow: 0 0 3px #0c9adc !important;\n"; 
echo "			-webkit-box-shadow: 0 0 3px #0c9adc !important;\n"; 
echo "		}\n"; 
echo "		#expValue\n"; 
echo "		{\n"; 
echo "			text-align:center;\n"; 
echo "			height:25px;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:13pt;\n"; 
echo "			color:#0c9adc;\n"; 
echo "			border-radius:4px;\n"; 
echo "			border:1px solid #cdcdcd;\n"; 
echo "			padding:2px;\n"; 
echo "			vertical-align: middle;\n"; 
echo "			transition: all 0.5s ease;\n"; 
echo "			-webkit-transition: all 0.5s ease;\n"; 
echo "			-moz-transition: all 0.5s ease;\n"; 
echo "		}\n"; 
echo "		#expValue:active,\n"; 
echo "		#expValue:focus\n"; 
echo "		{\n"; 
echo "			text-align:center;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:13pt;\n"; 
echo "			color:#333;\n"; 
echo "			border-radius:4px;\n"; 
echo "			border:1px solid #0c9adc !important;\n"; 
echo "			outline: none;\n"; 
echo "			//outline: 5px auto -webkit-focus-ring-color;\n"; 
echo "			//outline-offset: -3px;\n"; 
echo "			//outline-color: #00aeef;\n"; 
echo "			padding:2px;\n"; 
echo "			vertical-align: middle;\n"; 
echo "			box-shadow:0 0 3px #0c9adc !important;\n"; 
echo "			-moz-box-shadow: 0 0 3px #0c9adc !important;\n"; 
echo "			-webkit-box-shadow: 0 0 3px #0c9adc !important;\n"; 
echo "		}\n"; 
echo "		#expValue:hover\n"; 
echo "		{\n"; 
echo "			text-align:center;\n"; 
echo "			font-family:Arial;\n"; 
echo "			font-size:13pt;\n"; 
echo "			color:#333;\n"; 
echo "			border-radius:4px;\n"; 
echo "			border:1px solid #0c9adc !important;\n"; 
echo "			padding:2px;\n"; 
echo "			box-shadow:0 0 3px #0c9adc !important;\n"; 
echo "			-moz-box-shadow: 0 0 3px #0c9adc !important;\n"; 
echo "			-webkit-box-shadow: 0 0 3px #0c9adc !important;\n"; 
echo "			vertical-align: middle;\n"; 
echo "			transition: all 0.5s ease;\n"; 
echo "			-webkit-transition: all 0.5s ease;\n"; 
echo "			-moz-transition: all 0.5s ease;\n"; 
echo "		}\n"; 
echo "		iframe\n"; 
echo "		{\n"; 
echo "			margin-top:10px;\n"; 
echo "			width:750px;\n"; 
echo "			height:400px;\n"; 
echo "			border-top:1px solid #cdcdcd;\n"; 
echo "			border-radius:4px;\n"; 
echo "			padding:5px;\n"; 
echo "			box-shadow:0px 1px 2px rgba(0, 0, 0, 0.4);\n"; 
echo "			-moz-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.4);\n"; 
echo "			-webkit-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.4);\n"; 
echo "		}\n"; 
echo "		.spoiler\n"; 
echo "		{\n"; 
echo "			margin:0px;\n"; 
echo "		}\n"; 
echo "		.select\n"; 
echo "		{\n"; 
echo "			vertical-align:middle;\n"; 
echo "			background:url('http://gmtest.ru/wp-content/themes/mio/images/nav_bg.png') repeat-x scroll top center #f0f0f0;\n"; 
echo "			border: 1px solid #cdcdcd;\n"; 
echo "			border-radius: 4px;\n"; 
echo "			font-family: Arial;\n"; 
echo "			font-size: 13pt;\n"; 
echo "			padding: 5px;\n"; 
echo "			position: relative;\n"; 
echo "			color: #333;\n"; 
echo "			text-align: left;\n"; 
echo "			transition: all 0.5s ease;\n"; 
echo "			-webkit-transition: all 0.5s ease;\n"; 
echo "			-moz-transition: all 0.5s ease;\n"; 
echo "		}\n"; 
echo "		.select:hover\n"; 
echo "		{\n"; 
echo "			vertical-align:middle;\n"; 
echo "			background:url('http://gmtest.ru/wp-content/themes/mio/images/nav_bg.png') repeat-x scroll top center #f0f0f0;\n"; 
echo "			border: 1px solid #0c9adc !important;\n"; 
echo "			box-shadow:0 0 3px #0c9adc !important;\n"; 
echo "			-moz-box-shadow: 0 0 3px #0c9adc !important;\n"; 
echo "			-webkit-box-shadow: 0 0 3px #0c9adc !important;\n"; 
echo "			transition: all 0.5s ease;\n"; 
echo "			-webkit-transition: all 0.5s ease;\n"; 
echo "			-moz-transition: all 0.5s ease;\n"; 
echo "			border-radius: 4px;\n"; 
echo "			font-family: Arial;\n"; 
echo "			font-size: 13pt;\n"; 
echo "			padding: 5px;\n"; 
echo "			position: relative;\n"; 
echo "			text-align: left;\n"; 
echo "		}\n"; 
echo "		.select:active,\n"; 
echo "		.select:focus\n"; 
echo "		{\n"; 
echo "			vertical-align:middle;\n"; 
echo "			background:url('http://gmtest.ru/wp-content/themes/mio/images/nav_bg.png') repeat-x scroll top center #f0f0f0;\n"; 
echo "			border-radius: 4px;\n"; 
echo "			font-family: Arial;\n"; 
echo "			font-size: 13pt;\n"; 
echo "			padding: 5px;\n"; 
echo "			position: relative;\n"; 
echo "			text-align: left;\n"; 
echo "			border:1px solid #0c9adc !important;\n"; 
echo "			color: #333;\n"; 
echo "			outline: none;\n"; 
echo "			//outline: 5px auto -webkit-focus-ring-color;\n"; 
echo "			//outline-offset: -3px;\n"; 
echo "			//outline-color: #00aeef;\n"; 
echo "			box-shadow:0 0 3px #0c9adc !important;\n"; 
echo "			-moz-box-shadow: 0 0 3px #0c9adc !important;\n"; 
echo "			-webkit-box-shadow: 0 0 3px #0c9adc !important;\n"; 
echo "		}\n"; 
echo "		}\n"; 
echo "	</style>\n"; 
echo "	<script type=\"text/javascript\">\n"; 
echo "	    pass = prompt('Введите пароль:');\n"; 
echo "	    if (pass=='waiz') { } else { top.location.href=\"http://gmtest.ru/easy-steps/\" }\n"; 
echo "	    document.ondragstart = noselect; \n"; 
echo "	    // запрет на перетаскивание \n"; 
echo "	    document.onselectstart = noselect; \n"; 
echo "	    // запрет на выделение элементов страницы \n"; 
echo "	    document.oncontextmenu = noselect; \n"; 
echo "	    // запрет на выведение контекстного меню \n"; 
echo "	    function noselect() {return false;} \n"; 
echo "		function dsm()\n"; 
echo "				{\n"; 
echo "					var report = \"\";\n"; 
echo "					var labs = labValue.value.replace(',','.');\n"; 
echo "					var es = expValue.value.replace(',','.');\n"; 
echo "					var isValid1 = true;\n"; 
echo "					var isValid2 = true;\n"; 
echo "					var isValid3 = true;\n"; 
echo "					var isValid4 = true;\n"; 
echo "					var isValid5 = true;\n"; 
echo "					var isBlood = devices.value;\n"; 
echo "		\n"; 
echo "					if (!Number(labs)) \n"; 
echo "						{ document.getElementById('labValue').style.border = \"1px solid red\"; isValid2 = false; }\n"; 
echo "					else\n"; 
echo "						{ document.getElementById('labValue').style.border = \"1px solid #cdcdcd\"; }\n"; 
echo "								\n"; 
echo "					if (!Number(es)) \n"; 
echo "						{ document.getElementById('expValue').style.border = \"1px solid red\"; isValid3 = false; }\n"; 
echo "					else\n"; 
echo "						{ document.getElementById('expValue').style.border = \"1px solid #cdcdcd\"; }\n"; 
echo "					\n"; 
echo "					if (labs >= 0.5 && labs <= 50.0)\n"; 
echo "						{ document.getElementById('labValue').style.border = \"1px solid #cdcdcd\";}\n"; 
echo "					else\n"; 
echo "						{ document.getElementById('labValue').style.border = \"1px solid red\"; isValid4 = false;}	\n"; 
echo "					\n"; 
echo "					if (es >= 0.6 && es <= 33.3)\n"; 
echo "						{ document.getElementById('expValue').style.border = \"1px solid #cdcdcd\";}\n"; 
echo "					else\n"; 
echo "						{ document.getElementById('expValue').style.border = \"1px solid red\"; isValid5 = false;}	\n"; 
echo "						\n"; 
echo "					if (isBlood == -1) \n"; 
echo "						{ document.getElementById('devices').style.border = \"1px solid red\"; isValid1 = false; }\n"; 
echo "					else\n"; 
echo "						{ document.getElementById('devices').style.border = \"1px solid #cdcdcd\"; }\n"; 
echo "					\n"; 
echo "					if (!isValid1)\n"; 
echo "					{\n"; 
echo "						document.getElementById('report').className = \"rt_none\";\n"; 
echo "						document.getElementById('error1').style.display = \"block\";\n"; 
echo "						document.getElementById('error2').style.display = \"none\";\n"; 
echo "						document.getElementById('error3').style.display = \"none\";\n"; 
echo "						document.getElementById('error4').style.display = \"none\";\n"; 
echo "						document.getElementById('error5').style.display = \"none\";\n"; 
echo "						document.getElementById('error6').style.display = \"none\";\n"; 
echo "						document.getElementById('error7').style.display = \"none\";\n"; 
echo "						document.getElementById('error8').style.display = \"none\";\n"; 
echo "						document.getElementById('printer').style.display = \"none\";\n"; 
echo "						\n"; 
echo "						return;\n"; 
echo "					}\n"; 
echo "					\n"; 
echo "					\n"; 
echo "					if (!isValid2)\n"; 
echo "					{\n"; 
echo "						document.getElementById('report').className = \"rt_none\";\n"; 
echo "						document.getElementById('error1').style.display = \"none\";\n"; 
echo "						document.getElementById('error2').style.display = \"block\";\n"; 
echo "						document.getElementById('error3').style.display = \"none\";\n"; 
echo "						document.getElementById('error4').style.display = \"none\";\n"; 
echo "						document.getElementById('error4').style.display = \"none\";\n"; 
echo "						document.getElementById('error5').style.display = \"none\";\n"; 
echo "						document.getElementById('error6').style.display = \"none\";\n"; 
echo "						document.getElementById('error7').style.display = \"none\";\n"; 
echo "						document.getElementById('error8').style.display = \"none\";\n"; 
echo "						document.getElementById('printer').style.display = \"none\";\n"; 
echo "						\n"; 
echo "						return;\n"; 
echo "					}\n"; 
echo "					\n"; 
echo "					if (!isValid4)\n"; 
echo "					{\n"; 
echo "						document.getElementById('report').className = \"rt_none\";\n"; 
echo "						document.getElementById('error1').style.display = \"none\";\n"; 
echo "						document.getElementById('error2').style.display = \"none\";\n"; 
echo "						document.getElementById('error3').style.display = \"none\";\n"; 
echo "						document.getElementById('error4').style.display = \"none\";\n"; 
echo "						document.getElementById('error5').style.display = \"none\";\n"; 
echo "						document.getElementById('error6').style.display = \"none\";\n"; 
echo "						document.getElementById('error7').style.display = \"block\";\n"; 
echo "						document.getElementById('error8').style.display = \"none\";\n"; 
echo "						document.getElementById('printer').style.display = \"none\";\n"; 
echo "						\n"; 
echo "						return;\n"; 
echo "					}\n"; 
echo "					\n"; 
echo "					if (!isValid3)\n"; 
echo "					{\n"; 
echo "						document.getElementById('report').className = \"rt_none\";\n"; 
echo "						document.getElementById('error1').style.display = \"none\";\n"; 
echo "						document.getElementById('error2').style.display = \"none\";\n"; 
echo "						document.getElementById('error3').style.display = \"block\";\n"; 
echo "						document.getElementById('error4').style.display = \"none\";\n"; 
echo "						document.getElementById('error5').style.display = \"none\";\n"; 
echo "						document.getElementById('error6').style.display = \"none\";\n"; 
echo "						document.getElementById('error7').style.display = \"none\";\n"; 
echo "						document.getElementById('error8').style.display = \"none\";\n"; 
echo "						document.getElementById('printer').style.display = \"none\";\n"; 
echo "						\n"; 
echo "						return;\n"; 
echo "					}\n"; 
echo "					\n"; 
echo "					\n"; 
echo "					\n"; 
echo "					if (!isValid5)\n"; 
echo "					{\n"; 
echo "						document.getElementById('report').className = \"rt_none\";\n"; 
echo "						document.getElementById('error1').style.display = \"none\";\n"; 
echo "						document.getElementById('error2').style.display = \"none\";\n"; 
echo "						document.getElementById('error3').style.display = \"none\";\n"; 
echo "						document.getElementById('error4').style.display = \"none\";\n"; 
echo "						document.getElementById('error5').style.display = \"none\";\n"; 
echo "						document.getElementById('error6').style.display = \"block\";\n"; 
echo "						document.getElementById('error7').style.display = \"none\";\n"; 
echo "						document.getElementById('error8').style.display = \"none\";\n"; 
echo "						document.getElementById('printer').style.display = \"none\";\n"; 
echo "						\n"; 
echo "						return;\n"; 
echo "					}		\n"; 
echo "													\n"; 
echo "					var lab = parseFloat(labs)\n"; 
echo "					var e = parseFloat(es);\n"; 
echo "					\n"; 
echo "					if (isBlood == 1) lab = lab / 1.12;\n"; 
echo "					\n"; 
echo "					document.getElementById('error1').style.display = \"none\";\n"; 
echo "					document.getElementById('error2').style.display = \"none\";\n"; 
echo "					document.getElementById('error3').style.display = \"none\";\n"; 
echo "					document.getElementById('error4').style.display = \"none\";\n"; 
echo "					document.getElementById('error5').style.display = \"none\";\n"; 
echo "					document.getElementById('error6').style.display = \"none\";\n"; 
echo "					document.getElementById('error7').style.display = \"none\";\n"; 
echo "					document.getElementById('error8').style.display = \"none\";\n"; 
echo "					document.getElementById('printer').style.display = \"none\";\n"; 
echo "					\n"; 
echo "					\n"; 
echo "					if (lab <= 4.2)\n"; 
echo "					{			\n"; 
echo "						var lmtBot = lab - 0.83;\n"; 
echo "						var lmtTop = lab + 0.83;\n"; 
echo "					}\n"; 
echo "					else\n"; 
echo "					{\n"; 
echo "						var lmtBot = lab - lab * 0.2;\n"; 
echo "						var lmtTop = lab + lab * 0.2;\n"; 
echo "					};\n"; 
echo "					\n"; 
echo "					if (lab < 3.9)\n"; 
echo "					{\n"; 
echo "					document.getElementById('error4').style.display = \"block\";\n"; 
echo "					document.getElementById('error5').style.display = \"none\";\n"; 
echo "					document.getElementById('error8').style.display = \"none\";\n"; 
echo "					document.getElementById('printer').style.display = \"block\";\n"; 
echo "					\n"; 
echo "					}\n"; 
echo "					if (lab > 13.3)\n"; 
echo "					{\n"; 
echo "					document.getElementById('error5').style.display = \"block\";\n"; 
echo "					document.getElementById('error4').style.display = \"none\";\n"; 
echo "					document.getElementById('error8').style.display = \"none\";\n"; 
echo "					document.getElementById('printer').style.display = \"block\";\n"; 
echo "					\n"; 
echo "					}\n"; 
echo "					\n"; 
echo "					if (lab < 3.9 && e >= lmtBot && e <= lmtTop)\n"; 
echo "					{\n"; 
echo "					document.getElementById('error8').style.display = \"block\";\n"; 
echo "					document.getElementById('error4').style.display = \"none\";\n"; 
echo "					document.getElementById('error5').style.display = \"none\";\n"; 
echo "					document.getElementById('printer').style.display = \"block\";\n"; 
echo "					\n"; 
echo "					}\n"; 
echo "					if (lab > 13.3 && e >= lmtBot && e <= lmtTop)\n"; 
echo "					{\n"; 
echo "					document.getElementById('error8').style.display = \"block\";\n"; 
echo "					document.getElementById('error5').style.display = \"none\";\n"; 
echo "					document.getElementById('error4').style.display = \"none\";\n"; 
echo "					document.getElementById('printer').style.display = \"block\";\n"; 
echo "					\n"; 
echo "					}\n"; 
echo "												\n"; 
echo "			printText('Anal', Number(lab).toFixed(1) + \" ммоль/л\");\n"; 
echo "			printText('Anal1', Number(lab).toFixed(1) + \" ммоль/л\");\n"; 
echo "			printText('yourResult', Number(e).toFixed(1) + \" ммоль/л\");\n"; 
echo "			//printerText('yourResult1', Number(e).toFixed(1) + \" ммоль/л\");\n"; 
echo "			//printerText('yourResult2', Number(e).toFixed(1) + \" ммоль/л\");\n"; 
echo "			printText('yourRange', \"от \" + Number(lmtBot).toFixed(1) + \" до \" + Number(lmtTop).toFixed(1) + \" ммоль/л\");\n"; 
echo "			\n"; 
echo "			if (e >= lmtBot && e <= lmtTop)\n"; 
echo "			{\n"; 
echo "				printText('reportTitle', \"Ваш глюкометр измеряет точно!\");\n"; 
echo "				printText('testReport', \"Результат измерения находится в пределах допустимого диапазона\");\n"; 
echo "				printText('reportNote', \"Результат измерения вашего глюкометра соответствует мировому стандарту DIN EN ISO 15197:2003. Вы и ваш лечащий врач можете доверять показаниям прибора.\");\n"; 
echo "				document.getElementById('report').className = \"rt_green\";\n"; 
echo "				document.getElementById('error8').style.display = \"block\";\n"; 
echo "				document.getElementById('printer').style.display = \"block\";\n"; 
echo "			}\n"; 
echo "			else\n"; 
echo "			{\n"; 
echo "				printText('reportTitle', \"Осторожно! Ваш глюкометр измеряет НЕточно!\");\n"; 
echo "				printText('testReport', \"Результат измерения выходит за пределы допустимого диапазона\");\n"; 
echo "				document.getElementById('report').className = \"rt_red\";\n"; 
echo "				document.getElementById('printer').style.display = \"block\";\n"; 
echo "				if (e < lmtBot)\n"; 
echo "				{\n"; 
echo "					report += \"<b>Ваш глюкометр занижает показания на <span class = 'cube'>\" + Number(Math.abs(e - lmtBot)*100/lmtBot).toFixed(0) + \"%</span></b>\";\n"; 
echo "					report += \"<br/><br/><em>1. Вы рискуете пропустить ГИПЕРгликемию</em>.<br/><br/>Ваш уровень сахара в крови может быть значительно больше, чем показывает данный прибор. Повышенный уровень сахара в крови неизбежно ведёт к осложнениям диабета. Будьте осторожны!\";\n"; 
echo "				}\n"; 
echo "				if (e > lmtTop)\n"; 
echo "				{\n"; 
echo "					report += \"<b>Ваш глюкометр завышает показания на <span class = 'cube'>\" + Number(Math.abs(e - lmtTop)*100/lmtTop).toFixed(0) + \"%</span></b>\";\n"; 
echo "					report += \"<br /><br /><em>1. Вы рискуете пропустить ГИПОгликемию</em>.<br/><br/>Возможны ситуации, когда цифры, полученные на глюкометре будут вас устраивать. Но в реальности ваш уровень сахара будет близок к критически низкой отметке.<br/><br/><em>2. Вы рискуете превысить дозировку принимаемых препаратов</em>.<br/><br/>Глюкометр показывает уровень сахара выше, чем он есть в реальности. Лечащий врач может ошибочно назначить вам лечение, опираясь на показания данного прибора. Дозировки назначенных вам препаратов могут быть превышены!\";\n"; 
echo "				}\n"; 
echo "				printText('reportNote', report);\n"; 
echo "				\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "		\n"; 
echo "		function printText(s, v) { document.getElementById(s).innerHTML = v;}\n"; 
echo "		function f_Date(Str){ Str += \"\";\n"; 
echo "		if (Str.length==1) return (\"0\" + Str);\n"; 
echo "		else return Str;}\n"; 
echo "		</script>\n"; 
echo "</head>\n"; 
echo "<body class=\"body\">\n"; 
echo "  <table style=\"width: 860px; margin: 0px 0px 5px 19px;\">\n"; 
echo "  <tr>\n"; 
echo "  <td><p id=\"visible\" style=\"text-align: center; font-size: 17pt; color: #333; border-top: 1px solid #bdbdbd;border-bottom: 1px solid #bdbdbd; padding: 5px;margin-bottom: 10px;\">Заключение о проверке точности измерений глюкометра</p>\n"; 
echo "  </td>\n"; 
echo "  </tr>\n"; 
echo "  </table>\n"; 
echo "  <center><img id=\"invisible\" style=\"opacity:1; margin:7px auto 5px auto; border-top:1px solid #cdcdcd;box-shadow:0px 1px 2px rgba(0, 0, 0, 0.4);-moz-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.4);-webkit-box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.4); border-radius:4px;\" alt=\"\" src=\"http://gmtest.ru/wp-content/uploads/2013/10/title2.png\"/></center>\n"; 
echo "  <div class=\"container\"><div><div><button id=\"invisible\" class=\"play\" onmouseover=\"this.sv=this.style.backgroundColor; this.style.backgroundColor='#fff';\" onmouseout=\"if(this.sv)this.style.backgroundColor=this.sv; else this.style.backgroundColor='';\" onclick=\"this.parentNode.parentNode.childNodes[1].style.display = ''; this.parentNode.style.display = 'none'; return false;\" title=\"\"></button></div><div class=\"spoiler\" style=\"display: none;\"><div><button id=\"invisible\" class=\"play1\" onclick=\"this.parentNode.parentNode.parentNode.childNodes[0].style.display = ''; this.parentNode.parentNode.style.display = 'none'; return false;\" title=\"\"></button></div>\n"; 
echo "  <center><iframe id=\"logo\" title=\"Видео-инструкция\" src=\"http://www.youtube.com/embed/koNh2bmR2eg?rel=0\" allowfullscreen></iframe></center>\n"; 
echo "  </div></div></center>\n"; 
echo "    <table class=\"table\">\n"; 
echo "		<tr><td style=\"border-top: 1px solid #bdbdbd;padding: 5px;\" colspan=\"4\"></td></tr>\n"; 
echo "		<tr>\n"; 
echo "			<td><a style=\"margin: 0px 12px 0px 0px;\" class=\"number\">1</a></td>\n"; 
echo "	\n"; 
echo "	<td id=\"invisible\" class=\"text\" style=\"margin-top: 5px;\">Выберите модель глюкометра</td>\n"; 
echo "	<td id=\"visible\" class=\"text\" style=\"margin-top: 10px;\">Модель глюкометра</td>\n"; 
echo "	<td style=\"width: 8px;\"></td>\n"; 
echo "	<td colspan = \"1\"><select class=\"select\" required id = \"devices\">\n"; 
echo "  <option value=\"-1\">...</option>\n"; 
echo "  <option value=\"0\">Accu-Chek Active</option>\n"; 
echo "  <option value=\"0\">Accu-Chek Active New</option>\n"; 
echo "  <option value=\"0\">Accu-Chek Go</option>\n"; 
echo "  <option value=\"0\">Accu-Chek Go New</option>\n"; 
echo "  <option value=\"0\">Accu-Chek Mobile</option>\n"; 
echo "  <option value=\"0\">Accu-Chek Performa</option>\n"; 
echo "  <option value=\"0\">Accu-Chek Performa Nano</option>\n"; 
echo "  <option value=\"1\">Accutrend Plus</option>\n"; 
echo "  <option value=\"1\">Accutrend GC</option>\n"; 
echo "  <option value=\"1\">Ascensia Elite</option>\n"; 
echo "  <option value=\"1\">Ascensia Entrust</option>\n"; 
echo "  <option value=\"1\">Auto Sense</option>\n"; 
echo "  <option value=\"0\">Bionime Rightest GM300</option>\n"; 
echo "  <option value=\"0\">Bionime Rightest GM500</option>\n"; 
echo "  <option value=\"1\">BlueCare</option>\n"; 
echo "  <option value=\"0\">CareSens POP</option>\n"; 
echo "  <option value=\"0\">Clever Chek ТD-4209</option>\n"; 
echo "  <option value=\"0\">Clever Chek ТD-4227</option>\n"; 
echo "  <option value=\"0\">Contour TS</option>\n"; 
echo "  <option value=\"1\">Diabest</option>\n"; 
echo "  <option value=\"0\">Diacont</option>\n"; 
echo "  <option value=\"0\">EasyTouch GC</option>\n"; 
echo "  <option value=\"0\">EasyTouch GCHb</option>\n"; 
echo "  <option value=\"0\">EasyTouch GCU</option>\n"; 
echo "  <option value=\"0\">FreeStyle Papillon Mini</option>\n"; 
echo "  <option value=\"0\">iCheck</option>\n"; 
echo "  <option value=\"1\">IME-DC</option>\n"; 
echo "  <option value=\"1\">MultiCare-in</option>\n"; 
echo "  <option value=\"0\">OneTouch Horizon</option>\n"; 
echo "  <option value=\"0\">OneTouch Select</option>\n"; 
echo "  <option value=\"0\">OneTouch SelectSimple</option>\n"; 
echo "  <option value=\"0\">OneTouch Ultra</option>\n"; 
echo "  <option value=\"0\">OneTouch Ultra Easy</option>\n"; 
echo "  <option value=\"0\">OneTouch VerioPro+</option>\n"; 
echo "  <option value=\"0\">Optium Omega</option>\n"; 
echo "  <option value=\"0\">Optium Xceed</option>\n"; 
echo "  <option value=\"0\">SD Check Gold</option>\n"; 
echo "  <option value=\"1\">Sensocard</option>\n"; 
echo "  <option value=\"1\">Sensocard Plus</option>\n"; 
echo "  <option value=\"1\">SensoLite Nova</option>\n"; 
echo "  <option value=\"1\">SensoLite Nova Plus</option>\n"; 
echo "  <option value=\"1\">Super Glucocard 2</option>\n"; 
echo "  <option value=\"0\">TRUEresult twist</option>\n"; 
echo "  <option value=\"0\">WG-70 Slim</option>\n"; 
echo "  <option value=\"0\">WG-72 Voice</option>\n"; 
echo "  <option value=\"0\">Клевер Чек СКС-03</option>\n"; 
echo "  <option value=\"0\">Клевер Чек СКС-05</option>\n"; 
echo "  <option value=\"1\">Сателлит</option>\n"; 
echo "  <option value=\"1\">Сателлит Плюс</option>\n"; 
echo "  <option value=\"1\">Сателлит-Экспресс</option>\n"; 
echo "		    </select></td>\n"; 
echo "		    <td><span class=\"tip\" data-title=\"Вы не нашли свой глюкометр? Добавьте его в список программы, нажав на эту кнопку\"><a href=\"http://gmtest.ru/add-glucometer\" target=\"_blank\" class=\"plus\">+</a></span></td>\n"; 
echo "		    		</tr>\n"; 
echo "		    		<tr><td style=\"border-top: 1px solid #fff;padding: 3px;\" colspan = \"4\"></td></tr>\n"; 
echo "		    		<tr><td style=\"border-top: 1px solid #bdbdbd;padding: 3px;\" colspan = \"4\"></td></tr>\n"; 
echo "		    		<tr>\n"; 
echo "		    			<td><a style=\"margin: 0px 12px 0px 0px;\" class=\"number\">2</a></td>\n"; 
echo "		    			<td id=\"visible\" class=\"text\">Результат сахара в крови,<br/>полученный на лабораторном анализаторе</td>\n"; 
echo "		    			<td id=\"invisible\" class=\"text\">Введите результат сахара в крови,<br/>полученный на лабораторном анализаторе</td>\n"; 
echo "		    			<td style=\"width: 8px;\"></td>\n"; 
echo "		                <td><input type = \"text\" id = \"labValue\" size = \"3\" required /><a class=\"text\">ммоль/л</a></td>\n"; 
echo "		    		</tr>\n"; 
echo "		    		<tr><td style=\"border-top: 1px solid #fff;padding: 1px;\" colspan = \"4\"></td></tr>\n"; 
echo "		    		<tr><td style=\"border-top: 1px solid #bdbdbd;padding: 3px;\" colspan = \"4\"></td></tr>\n"; 
echo "		    		<tr>\n"; 
echo "		    			<td><a style=\"margin: 0px 12px 0px 0px;\" class=\"number\">3</a></td>\n"; 
echo "		    			<td id=\"invisible\" class=\"text\">Введите результат сахара в крови,<br/>полученный с помощью глюкометра</td>\n"; 
echo "		    			<td id=\"visible\" class=\"text\">Результат сахара в крови,<br/>полученный с помощью глюкометра</td>\n"; 
echo "		    			<td style=\"width: 8px;\"></td>\n"; 
echo "		                <td><input type = \"text\" id = \"expValue\" size = \"3\" required /><a class=\"text\">ммоль/л</a></td>\n"; 
echo "		    		</tr>\n"; 
echo "		    		<tr><td style=\"border-top: 1px solid #fff;padding: 1px;\" colspan = \"4\"></td></tr>\n"; 
echo "		    		<tr><td style=\"border-top: 1px solid #bdbdbd;padding: 3px;\" colspan = \"4\"></td></tr>\n"; 
echo "		    		<tr id=\"invisible\">\n"; 
echo "		    			<td><a style=\"margin: 0px 12px 0px 0px;\" class=\"number\">4</a></td>\n"; 
echo "		    			<td class=\"text\">Нажмите кнопку \"проверить\" и узнайте<br/>насколько точно измеряет глюкометр</td>\n"; 
echo "		    			<td style=\"width: 8px;\"></td>\n"; 
echo "		                <td colspan = \"2\"><a style=\"margin-left:2px;\" class=\"button\" onclick = \"dsm()\" href=\"#view\">Проверить</a></td>\n"; 
echo "		    		</tr>\n"; 
echo "		    		<tr id=\"invisible\"><td style=\"border-top: 1px solid #fff;padding: 1px;\" colspan = \"4\"></td></tr>\n"; 
echo "		    		<tr id=\"invisible\"><td style=\"border-top: 1px solid #bdbdbd;padding: 3px;\" colspan = \"4\"></td></tr>\n"; 
echo "		    	</table>\n"; 
echo "		       \n"; 
echo "		    	\n"; 
echo "		    	<table id = \"report\" class = \"rt_none\" style=\"margin-top: 10px;\">\n"; 
echo "		    		<tr id=\"view\">\n"; 
echo "		    		    <td colspan = \"3\" id = \"reportTitle\"></td>\n"; 
echo "		    		</tr>\n"; 
echo "		    		<tr>\n"; 
echo "		                <td class=\"text\" style=\"text-align:center; width:275px;\">Результат измерения, полученный на вашем глюкометре</td>\n"; 
echo "		    			<td class=\"text\" style=\"text-align:center; width:275px;\">Допустимый диапазон измерений для вашего глюкометра</td>\n"; 
echo "		    			<td class=\"text\" style=\"text-align:center;\">Результат проверки</td>\n"; 
echo "		    		</tr>\n"; 
echo "		    		<tr>\n"; 
echo "		                <td id = \"yourResult\"></td>\n"; 
echo "		    			<td id = \"yourRange\"></td>\n"; 
echo "		    			<td id = \"testReport\"></td>\n"; 
echo "		    		</tr>\n"; 
echo "		    		<tr>\n"; 
echo "		                <td colspan = \"3\">\n"; 
echo "		    				<table class=\"report_note\"><tr><td id = \"reportNote\"></td></tr></table>\n"; 
echo "		    			</td>\n"; 
echo "		    		</tr>\n"; 
echo "		    	</table>\n"; 
echo "		    	<div id = \"error1\">\n"; 
echo "		    		<p style=\"color:#ed1c24;\">Ошибка! Выберите модель глюкометра.</p>\n"; 
echo "		    	</div>\n"; 
echo "		    	<div id = \"error2\">\n"; 
echo "		    		<p style=\"color:#ed1c24;\">Ошибка! Введите результат сахара в крови,<br/>полученный на лабораторном анализаторе.</p>\n"; 
echo "		    	</div>\n"; 
echo "		    	<div id = \"error7\">\n"; 
echo "		    		<p style=\"color:#ed1c24;\">Ошибка! Введенное значение выходит за пределы диапазона измерений лабораторного анализатора (0.5 ммоль/л - 50.5 ммоль/л).</p>\n"; 
echo "		    	</div>\n"; 
echo "		    	<div id = \"error3\">\n"; 
echo "		    		<p style=\"color:#ed1c24;\">Ошибка! Введите результат сахара в крови,<br/>полученный с помощью глюкометра.</p>\n"; 
echo "		    	</div>\n"; 
echo "		    	<div id = \"error4\">\n"; 
echo "		    	<table class=\"rt_red\">\n"; 
echo "		    	<tr>\n"; 
echo "		    	<td style=\"vertical-align: middle;border-bottom: 1px solid red;\"><p style=\"margin: 5px;\"><img style=\"vertical-align: middle;margin-top: -5px; margin-right: -5px;\" alt=\"внимание\" src=\"http://gmtest.ru/wp-content/uploads/2013/10/ahtung1.png\"><span style=\"color:#ed1c24; font-weight: normal;font-size: 14pt;margin: 10px 20px 0px 20px;\">Ваше истинное значение сахара в крови <span style=\"color: #333;\" class = 'cube' id=\"Anal\"></span>(лабораторный анализ)</span></p>\n"; 
echo "		    	</td>\n"; 
echo "		    	</tr>\n"; 
echo "		    	<tr>\n"; 
echo "		    	<td>\n"; 
echo "		    	<table class=\"report_note\"><tr><td>Будьте внимательны! Если уровень сахара в крови ниже 3.9 ммоль/л, срочно съешьте сладкое, чтобы избежать гипогликемической комы или летального исхода. Либо примите меры, рекомендованные вашим врачом.</td></tr></table>\n"; 
echo "		    	</td>\n"; 
echo "		    		</tr>\n"; 
echo "		    	</table>\n"; 
echo "		    	</div>\n"; 
echo "		    	<div id = \"error5\">\n"; 
echo "		    	<table class=\"rt_red\">\n"; 
echo "		    	<tr>\n"; 
echo "		    	<td style=\"vertical-align: middle;border-bottom: 1px solid red;\"><p style=\"margin: 5px;\"><img style=\"vertical-align: middle;margin-top: -5px; margin-right: -5px;\" alt=\"внимание\" src=\"http://gmtest.ru/wp-content/uploads/2013/10/ahtung1.png\"><span style=\"color:#ed1c24; font-weight: normal;font-size: 14pt;margin: 10px 20px 0px 20px;\">Ваше истинное значение сахара в крови <span style=\"color: #333;\" class = 'cube' id=\"Anal1\"></span>(лабораторный анализ)</span></p>\n"; 
echo "		    	</td>\n"; 
echo "		    	</tr>\n"; 
echo "		    	<tr>\n"; 
echo "		    	<td>\n"; 
echo "		    	<table class=\"report_note\"><tr><td>Будьте внимательны! Когда сахар в крови превышает 13.3 ммоль/л, необходимо снижать его уровень. Обратитесь к врачу или примите рекомендованные им меры.</td></tr></table>\n"; 
echo "		    	</td>\n"; 
echo "     	    	</tr>\n"; 
echo "		    	</table>\n"; 
echo "		    	</div>\n"; 
echo "		    	<div id = \"error6\">\n"; 
echo "		    		<p style=\"color:#ed1c24;\">Ошибка! Введенное значение выходит за пределы диапазона измерений глюкометра (0.6 ммоль/л - 33.3 ммоль/л).</p>\n"; 
echo "		    	</div>\n"; 
echo "		    	<div id = \"error8\">\n"; 
echo "		    	<table class=\"rt_gray\">\n"; 
echo "		    	<tr>\n"; 
echo "		    	<td style=\"vertical-align: middle;border-bottom: 1px solid #b9b9b9;\"><p style=\"margin: 5px;\"><img style=\"vertical-align: middle;margin-top: -5px; margin-right: -5px;\" alt=\"внимание\" src=\"http://gmtest.ru/wp-content/uploads/2013/10/ahtung.png\"><span style=\"color:#333; font-weight: normal;font-size: 14pt;margin: 10px 20px 0px 20px;\">Общие рекомендации</span></p>\n"; 
echo "		    	</td>\n"; 
echo "		    	</tr>\n"; 
echo "		    	<tr>\n"; 
echo "		    	<td>\n"; 
echo "		    	<table class=\"report_note\"><tr><td>Несмотря на то, что ваш глюкометр измеряет точно, будьте внимательны к цифрам, отражающим ваш уровень сахара в крови.<br/><br/>Результаты <b>ниже 3.9 ммоль/л или выше 13.3 ммоль/л</b> опасны осложнениями диабета. Вы можете сомневаться в полученных результатах, потому что хорошо себя чувствуете. Во избежание ошибок - повторите измерение.<br/><br/>Если уровень сахара по-прежнему низкий или высокий, обратитесь за помощью к врачу или примите рекомендованные им меры.</td></tr></table>\n"; 
echo "		    	</td>\n"; 
echo "		    		</tr>\n"; 
echo "		    	</table>\n"; 
echo "		    	</div>\n"; 
echo "		        <div id=\"printer\"><center><a style=\"margin-bottom: 10px;\" class=\"button\" id=\"print_button\" onclick=\"window.print()\">Распечатать</a></center></div>\n"; 
echo "		        <p id=\"visible\" style=\"width: 304px; text-align: left; font-size: 10pt; margin: 20px 0px 10px 20px; border: 1px solid #bdbdbd; padding: 7px; border-radius: 4px;\">Дата проведения проверки:<span style=\"border-bottom: 1px solid #bdbdbd; margin-left: 15px;\">\n"; 
echo "		        <script language=\"javascript\" type=\"text/javascript\">\n"; 
echo "		        var d = new Date();\n"; 
echo "		        var month=new Array(\"января\",\"февраля\",\"марта\",\"апреля\",\"мая\",\"июня\",\"июля\",\"августа\",\"сентября\",\"октября\",\"ноября\",\"декабря\");\n"; 
echo "		        document.write(d.getDate()+ \" \" + month[d.getMonth()] + \" \" + d.getFullYear() + \" г.\");\n"; 
echo "		        </script></span><br /><br />Время проведения проверки:<span style=\"border-bottom: 1px solid #bdbdbd; margin-left: 5px;\">\n"; 
echo "		        <script language=\"javascript\" type=\"text/javascript\">\n"; 
echo "		        var d = new Date();\n"; 
echo "		        document.write(f_Date(d.getHours()) + \":\" + f_Date (d.getMinutes()));\n"; 
echo "		        </script></span></p>\n"; 
echo "		        <table id=\"visible1\" style=\"width: 860px; margin-left: 19px;\">\n"; 
echo "		        <tr>\n"; 
echo "		        <td id=\"visible\" style=\"width: 860px; border-bottom: 1px solid #bdbdbd;\">\n"; 
echo "		        </td>\n"; 
echo "		        </tr>\n"; 
echo "		        <tr>\n"; 
echo "		        <td><p id=\"visible\" style=\"text-align: left;font-size: 9pt;margin: 0px;padding: 2px 0px 0px 0px;\">Используя данные, полученные с помощью программы, вы принимаете условия пользовательского соглашения (См. на обороте страницы).</p>\n"; 
echo "		        </td>\n"; 
echo "		        </tr>\n"; 
echo "		        <tr>\n"; 
echo "		        <td id=\"invisible\" style=\"width: 860px; border-bottom: 1px solid #bdbdbd;\">\n"; 
echo "		        </td>\n"; 
echo "		        </tr>\n"; 
echo "		        <tr>\n"; 
echo "		        <td id=\"invisible\">\n"; 
echo "		        <p  style=\"text-align: left;font-size: 9pt;margin: 0px;padding: 4px 0px 0px 0px;\">Используя программу, вы принимаете условия пользовательского соглашения. <a class=\"link\" href=\"http://gmtest.ru/prog_terms\" target=\"_blank\" title=\"\">Подробнее</a></p>\n"; 
echo "		        </td>\n"; 
echo "		        </tr>\n"; 
echo "		        <tr>\n"; 
echo "		        <td id=\"invisible\">\n"; 
echo "		        <p style=\"text-align: left; font-size: 9pt; margin: 0px 0px 3px 0px;\">В программе используется методика расчета, основанная на мировом стандарте DIN EN ISO 15197:2003. <a class=\"link\" href=\"http://gmtest.ru/calc_proc\" target=\"_blank\" title=\"\">Подробнее</a></p>\n"; 
echo "		        </td>\n"; 
echo "		        </tr>\n"; 
echo "		        </table>\n"; 
echo "		        <table style=\"width: 860px;margin-left: 19px;margin-top: -5px;\">\n"; 
echo "		        <tr>\n"; 
echo "		        <td id=\"visible\" style=\"border-top: 1px solid #bdbdbd;\"><p style=\"text-align: left; font-size: 10pt; margin: 0px 0px -7px 0px; padding: 5px 0px 10px 0px;\">Программа является интеллектуальной собственностью проекта \"МЕРИДИАН\" и предназначена для индивидуального использования.<br/>Использование программы в иных целях разрешено только с письменного согласия разработчика (http://gmtest.ru/about_es).</p>\n"; 
echo "		        </td>\n"; 
echo "		        </tr>\n"; 
echo "		        <tr>\n"; 
echo "		        <td id=\"visible\" style=\"border-top: 1px solid #bdbdbd;width: 860px;\">\n"; 
echo "		        </td>\n"; 
echo "		        </tr>\n"; 
echo "		        </table>\n"; 
echo "		        <table id=\"visible1\" style=\"width: 860px; margin-left: 19px;\">\n"; 
echo "		        <tr>\n"; 
echo "		        <td id=\"invisible\" style=\"border-top: 1px solid #bdbdbd;\"><p style=\"text-align: left; font-size: 9pt; margin: 0px 0px -3px 0px; padding: 8px 0px 8px 0px;\">Программа является интеллектуальной собственностью проекта \"МЕРИДИАН\" и предназначена для индивидуального использования.<br/>Использование программы в иных целях разрешено только с письменного согласия разработчика. <a class=\"link\" href=\"http://gmtest.ru/about_es\" target=\"_blank\" title=\"\">Подробнее</a></p>\n"; 
echo "		        </td>\n"; 
echo "		        </tr>\n"; 
echo "		        <tr>\n"; 
echo "		        <td id=\"invisible\" style=\"border-top: 1px solid #bdbdbd; width: 860px;\">\n"; 
echo "		        </td>\n"; 
echo "		        </tr>\n"; 
echo "		        <tr>\n"; 
echo "		        <td>\n"; 
echo "		        </td>\n"; 
echo "		        </tr>\n"; 
echo "		        <tr>\n"; 
echo "		        <td>\n"; 
echo "		        </td>\n"; 
echo "		        </tr>\n"; 
echo "		        <tr>\n"; 
echo "		        <td>\n"; 
echo "		        </td>\n"; 
echo "		        </tr>\n"; 
echo "		        </table>\n"; 
echo "		        <table id=\"visible\" class=\"more\" style=\"width:860px; margin-left:19px; \" >\n"; 
echo "		            <tr>\n"; 
echo "		            <td><p style=\"text-align:center; font-family:Arial; font-size:9pt; font-weight:bold; color:#333333; margin-bottom:0px;\">Пользовательское соглашение</p>\n"; 
echo "		            </td>\n"; 
echo "		            </tr>\n"; 
echo "		            <tr>\n"; 
echo "		            <td style=\"text-align:left; font-family:Arial; font-size:8pt; color:#333333;\">\n"; 
echo "		            Скачивание и любое использование программы означает, что вы полностью прочитали, поняли и выразили своё согласие с условиями нижеизложенного соглашения, обязуетесь соблюдать эти условия и нести ответственность за их нарушение.\n"; 
echo "		            <ol style=\"margin: 0px 0px 0px -10px;\">\n"; 
echo "		            <li style=\"margin: 3px 0px 2px 0px;\">Программа проверки точности глюкометра «Easy Steps» является бесплатно распространяемым программным обеспечением.</li>\n"; 
echo "		            <li style=\"margin: 3px 0px 2px 0px;\">Программа проверки точности глюкометра «Easy Steps» предназначена для свободного ознакомления Пользователя со сравнением результатов измерений, полученных на лабораторном анализаторе и на глюкометре путем ввода необходимых данных в соответствующие поля.<br/>\n"; 
echo "		            Более подробное описание принципа работы программы есть на её странице в видео-инструкции, с которой Пользователю необходимо ознакомиться прежде, чем приступать к работе с программой проверки точности глюкометра «Easy Steps».</li>\n"; 
echo "		            <li style=\"margin: 3px 0px 2px 0px;\">Все заключения о результатах измерений, отображаемые в программе проверки точности глюкометра «Easy Steps», соответствуют требованиям мирового стандарта DIN EN ISO 15197:2003.<br/>\n"; 
echo "		            Настоящий стандарт предназначен для систем мониторинга глюкозы в крови, используемых непрофессионалами, и устанавливает требования непосредственно к приборам самоконтроля концентрации глюкозы в крови, включая сведения, представляемые изготовителем.</li>\n"; 
echo "		            <li style=\"margin: 3px 0px 2px 0px;\">Разработчики и Владельцы этой программы не несут никакой ответственности за дальнейшие намерения Пользователя в использовании полученных результатов и заключений где-либо. Использование результатов и заключений, полученных с помощью программы,  осуществляется исключительно по вашему усмотрению и на ваш риск.</li>\n"; 
echo "		            <li style=\"margin: 3px 0px 2px 0px;\">Программа находится в свободном доступе, и пользователи имеют право на её неограниченную установку, запуск, а также свободное использование и изучение.</li>\n"; 
echo "		            <li style=\"margin: 3px 0px 2px 0px;\">Любая модификация (изменение, улучшение) программы проверки точности глюкометра «Easy Steps» с целью её дальнейшего опубликования разрешена только с письменного согласия Разработчика, ввиду возможности введения пользователей в заблуждение и возникновения вытекающих из этого последствий.</li>\n"; 
echo "		            <li style=\"margin: 3px 0px 2px 0px;\">Запрещается любое коммерческое использование программы проверки точности глюкометра «Easy Steps» с целью получения денежной или иной выгоды.</li>\n"; 
echo "		            </ol>\n"; 
echo "		            </td>\n"; 
echo "		            </tr>\n"; 
echo "		            <tr>\n"; 
echo "		            <td><p style=\"text-align:center; font-family:Arial; font-size:9pt; font-weight:bold; color:#333333; margin-top: 0px; margin-bottom:2px;\">Методика расчета, заложенная в программе \"Easy Steps\".</p>\n"; 
echo "		             </td>\n"; 
echo "		             </tr>\n"; 
echo "		             <tr>\n"; 
echo "		             <td style=\"text-align:left; font-family:Arial; font-size:8pt; color:#333333;\">\n"; 
echo "		             Существует международный стандарт DIN EN ISO 15197:2003, который устанавливает соответствующие требования для систем мониторинга глюкозы в крови, используемых непрофессионалами, и устанавливает требования непосредственно к приборам самоконтроля концентрации глюкозы в крови, включая сведения, представляемые изготовителем. Согласно данному стандарту точность глюкометров должна быть следующей:<br>\n"; 
echo "		             \n"; 
echo "		             <p style=\"margin: 3px 0px 3px 0px;text-align:left; font-family:Arial; font-size:8pt; color:#333333;\">При уровне глюкозы в крови НИЖЕ 75 мг/дл (4,2 ммоль/л) 95% всех измерений, выполненных с помощью глюкометра, должны отличаться от эталона (измерения, выполненного на эталонном анализаторе глюкозы) не более чем на 15 мг/дл (0,83 ммоль/л) как в большую, так и в меньшую сторону.<br>\n"; 
echo "		             \n"; 
echo "		             При концентрации глюкозы в крови ВЫШЕ или РАВНОЙ 75 мг/дл (4,2 ммоль/л) 95% всех измерений, выполненных с помощью глюкометра, должны отличаться от эталона (измерения, выполненного на эталонном анализаторе глюкозы) не более чем на 20% как в большую, так и в меньшую сторону.</p>\n"; 
echo "		             \n"; 
echo "		             На основании этого стандарта точности программа \"Easy Steps\" рассчитывает предельно допустимый диапазон измерений для глюкометра и, сравнивая эти измерения с показаниями лабораторного анализатора, формирует заключение о проверке. Ниже вы можете ознакомиться с алгоритмом проверки более детально. Обратите внимание, что в данной программе глюкометры должны сравниваться <span style=\"text-decoration:underline;\">только с теми анализаторами, чьи показатели эквивалентны плазме крови</span>.\n"; 
echo "		             \n"; 
echo "		             <p style=\"margin: 1px 0px 1px 0px;text-align:left; font-family:Arial; font-size:8pt; color:#333333;\"><b>Ввод расчётных данных и запуск программы</b></p>\n"; 
echo "		             \n"; 
echo "		             Шаг 1. Необходимо выбрать модель глюкометра из выплывающего списка. Как только прибор выбран, программа сама определяет принцип его калибровки.<br>\n"; 
echo "		             \n"; 
echo "		             Шаг 2. Необходимо указать результат измерения, полученный на лабораторном анализаторе.<br>\n"; 
echo "		             \n"; 
echo "		             Шаг 3. Необходимо указать результат измерения, полученный на глюкометре.<br>\n"; 
echo "		             \n"; 
echo "		             Шаг 4. Необходимо нажать кнопку «Проверить», чтобы запустить программу.<br>\n"; 
echo "		             \n"; 
echo "		             <p style=\"margin: 1px 0px 1px 0px;text-align:left; font-family:Arial; font-size:8pt; color:#333333;\"><b>Расчёт предельно допустимого диапазона измерений для глюкометра</b>.</p>\n"; 
echo "		             \n"; 
echo "		             <b><em>Л</em></b> – результат измерения, полученный на лабораторном анализаторе.<br>\n"; 
echo "		             \n"; 
echo "		             <b><em>Г</em></b> – результат измерения, полученный на глюкометре.<br>\n"; 
echo "		             \n"; 
echo "		             <b><em>НЗ</em></b> – нижнее значение предельно допустимого диапазона измерений глюкометра.<br>\n"; 
echo "		             \n"; 
echo "		             <b><em>ВЗ</em></b> –  верхнее значение предельно допустимого диапазона измерений глюкометра.<br>\n"; 
echo "		             <b><em>ВО</em></b> – величина отклонения.<br>\n"; 
echo "		             \n"; 
echo "		             <p style=\"margin: 2px 0px 0px 0px;text-align:left; font-family:Arial; font-size:8pt; color:#333333;\">При выборе глюкометра, <span style=\"text-decoration:underline;\">калиброванного по плазме крови</span>, алгоритм расчета будет следующий:</p>\n"; 
echo "		             \n"; 
echo "		             <ol style=\"margin: 0px 0px 0px -10px;\">\n"; 
echo "		             <li style=\"list-style:lower-latin;margin: 2px 0px 2px 0px;\">Если «<em>Л</em>» ниже 4,2 ммоль/л, то:</li>\n"; 
echo "		             <ul style=\"margin: 0px 0px 0px -10px;\">\n"; 
echo "		             <li style=\"list-style:disc;margin: 2px 0px 0px 0px;\"><b><em>НЗ = Л – 0,83 ммоль/л</em></b> (Пример: предположим, что <em>Л</em> = 4,0 ммоль/л. Тогда <em>НЗ</em> = 4 – 0,83. Таким образом, <em>НЗ</em> = 3,17 ммоль/л (округляем до 3,2 ммоль/л));</li>\n"; 
echo "		             <li style=\"list-style:disc;margin: 0px 0px 2px 0px;\"><b><em>ВЗ = Л + 0,83 ммоль/л</em></b> (Пример: предположим, что <em>Л</em> = 4,0 ммоль/л. Тогда <em>НЗ</em> = 4 + 0,83. Таким образом, <em>ВЗ</em> = 4,83 ммоль/л (округляем до 4,8 ммоль/л));</li>\n"; 
echo "		             </ul>\n"; 
echo "		             \n"; 
echo "		             <li style=\"list-style:lower-latin;margin: 2px 0px 2px 0px;\">Если «<em>Л</em>» выше или равен 4,2 ммоль/л, то:</li>\n"; 
echo "		             <ul style=\"margin: 0px 0px 0px -10px;\">\n"; 
echo "		             <li style=\"list-style:disc;margin: 2px 0px 0px 0px;\"><b><em>НЗ = Л – 20%</em></b> (Пример: предположим, что <em>Л</em> = 5,0 ммоль/л. Тогда <em>НЗ</em> = 5 – 20%. Таким образом, <em>НЗ</em> = 4,0 ммоль/л);</li>\n"; 
echo "		             <li style=\"list-style:disc;margin: 0px 0px 2px 0px;\"><b><em>ВЗ = Л + 20%</em></b> (Пример: предположим, что <em>Л</em> = 5,0 ммоль/л. Тогда <em>НЗ</em> = 5 + 20%. Таким образом, <em>ВЗ</em> = 6,0 ммоль/л);</li>\n"; 
echo "		             </ul>\n"; 
echo "		             </ol>\n"; 
echo "		             \n"; 
echo "		             <p style=\"margin: 2px 0px -7px 0px;text-align:left; font-family:Arial; font-size:8pt; color:#333333;\">При выборе глюкометра, <span style=\"text-decoration:underline;\">калиброванного по цельной крови</span>, алгоритм расчета будет следующий:</p>\n"; 
echo "		             \n"; 
echo "		             <ol style=\"margin-left: -10px;\">\n"; 
echo "		             <li style=\"list-style:lower-latin;margin: 2px 0px 2px 0px;\">«<em>Л</em>» (поскольку именно лабораторный анализатор является эталонным прибором) делится на 1,12 (т.к. в плазме показатели сахара крови примерно на 12% выше чем в цельной крови), тем самым результаты лабораторного анализатора по плазме пересчитываются в результаты по цельной крови</li>\n"; 
echo "		             <li style=\"list-style:lower-latin;margin: 2px 0px -7px 0px;\">Далее процедура расчета предельно допустимого диапазона для глюкометра будет развиваться по тому же сценарию, который был описан для глюкометра <em>калиброванного по плазме крови</em> в пункте «а»</li>\n"; 
echo "		             </ol>\n"; 
echo "		             \n"; 
echo "		             <p style=\"margin: 0px 0px 1px 0px;text-align:left; font-family:Arial; font-size:8pt; color:#333333;\"><b>Формирование заключения о проверке глюкометра</b></p>\n"; 
echo "		             \n"; 
echo "		             После того как определён предельно допустимый диапазон, программа проверяет попал ли в него результат измерения, полученный с помощью глюкометра. Если да, то программа формирует заключение о том, что глюкометр измеряет точно. Если нет, то программа формирует заключение о том, что глюкометр измеряет неточно, а так же фиксирует %, на который прибор завысил или занизил результаты измерений.<br>\n"; 
echo "		             \n"; 
echo "		             <p style=\"margin: 1px 0px 1px 0px;text-align:left; font-family:Arial; font-size:8pt; color:#333333;\"><b>Расчёт величины отклонений</b></p>\n"; 
echo "		             \n"; 
echo "		             <p style=\"margin: 2px 0px 0px 0px;text-align:left; font-family:Arial; font-size:8pt; color:#333333;\">Если результат измерения, полученный на глюкометре, <span style=\"text-decoration:underline;\">ниже</span> чем нижняя граница предельно допустимого диапазона, то программа считает насколько прибор <em>занижает</em> показания по формуле:</p>\n"; 
echo "		             \n"; 
echo "		             <ul style=\"margin: 2px 0px 3px -10px;\">\n"; 
echo "		             <li style=\"list-style:disc;margin: 3px 0px 3px 0px;\"><b><em>ВО = (НЗ – Г)/НЗ*100%</em></b> (Пример: предположим, что <em>Г</em> = 4,0 ммоль/л, <em>НЗ</em> =  4,8 ммоль/л.\n"; 
echo "		             Тогда <em>ВO</em> = (4,8 – 4,0)/4,8*100% = 16,7% (округляем до 17%));</li>\n"; 
echo "		             </ul>\n"; 
echo "		             \n"; 
echo "		             <p style=\"margin: 2px 0px 0px 0px;text-align:left; font-family:Arial; font-size:8pt; color:#333333;\">Если результат измерения, полученный на глюкометре, <span style=\"text-decoration:underline;\">выше</span> чем верхняя граница предельно допустимого диапазона, то программа считает насколько прибор <em>завышает</em> показания по формуле:</p>\n"; 
echo "		             \n"; 
echo "		             <ul style=\"margin: 2px 0px 2px -10px;\">\n"; 
echo "		             <li style=\"list-style:disc;margin: 2px 0px 2px 0px;\"><b><em>ВО = (Г – ВЗ)/ВЗ*100%</em></b> (Пример: предположим, что <em>Г</em> = 8,0 ммоль/л, <em>НЗ</em> =  7,2 ммоль/л.\n"; 
echo "		             Тогда <em>ВO</em> = (8,0 – 7,2)/7,2*100% = 11,1% (округляем до 11%));</li>\n"; 
echo "		             </ul>\n"; 
echo "		             \n"; 
echo "		             <p style=\"margin: 1px 0px 1px 0px;text-align:left; font-family:Arial; font-size:8pt; color:#333333;\"><b>Комментарии с рекомендациями</b></p>\n"; 
echo "		             \n"; 
echo "		             Если результат измерения, полученный на лабораторном анализаторе ниже 3,9 ммоль/л или выше 13,3 ммоль/л (значения сахара в крови, на которые пользователю стоит обратить более пристальное внимание), то программа сформирует рекомендации для пользователя глюкометра.<br>\n"; 
echo "		             \n"; 
echo "		             <p style=\"margin: 1px 0px 0px 0px;text-align:left; font-family:Arial; font-size:8pt; color:#333333;\"><b>Уведомления об ошибках при работе с программой</b></p>\n"; 
echo "		             \n"; 
echo "		             <ol style=\"margin: 2px 0px 2px -10px;\">\n"; 
echo "		             <li style=\"list-style:lower-latin;margin: 2px 0px 2px 0px;\">– «Ошибка! Выберите модель вашего глюкометра»;<br>\n"; 
echo "		             – «Ошибка! Введите результат вашего сахара в крови, полученный на лабораторном анализаторе»;<br>\n"; 
echo "		             – «Ошибка! Введите результат вашего сахара в крови, полученный с помощью глюкометра».<br>\n"; 
echo "		             Перечисленные ошибки появляются, если один из шагов (выбор модели глюкометра, ввод результатов измерений анализатора или люкометра) не будет выполнен.</li>\n"; 
echo "		             \n"; 
echo "		             <li style=\"list-style:lower-latin;margin: 2px 0px 2px 0px;\">– «Ошибка! Введенное значение выходит за пределы диапазона измерений лабораторного анализатора (0,5 ммоль/л – 50,5 ммоль/л)». Ошибка появляется, если результат измерения, полученный на лабораторном анализаторе, выйдет за пределы рабочего диапазона: 0,5 – 50,5 ммоль/л. Этот рабочий диапазон взят как максимально возможный для существующих на территории России лабораторных анализаторов.</li>\n"; 
echo "		             <li style=\"list-style:lower-latin;margin: 2px 0px 2px 0px;\">– «Ошибка! Введенное значение выходит за пределы диапазона измерений глюкометра (0,6 ммоль/л – 33,3 ммоль/л)». Ошибка появляется, если результат измерения, полученный при помощи глюкометра, выйдет за пределы рабочего диапазона: 0,6 – 33,3 ммоль/л. Этот рабочий диапазон взят как максимально возможный для существующих на территории России глюкометров.</li>\n"; 
echo "		             </ol>\n"; 
echo "		             </td>\n"; 
echo "		             </tr>\n"; 
echo "		             </table>\n"; 
echo "		        </div>\n"; 
echo "		    </body>\n"; 
echo "		    </html>\n";
?>